In [1]:
import pandas as pd
import requests
import json

# **API REQUETE GLOBALE** #

In [2]:
# CALL API
API_KEY = "haj00y9FzSQ1VZCTUjpmla8Q98xRnA6a"

URL = 'https://prim.iledefrance-mobilites.fr/marketplace/disruptions_bulk/disruptions/v2'

headers = {
    "Accept": "application/json",
    "apikey": API_KEY
}

response = requests.get(URL, headers=headers)

if response.status_code == 200:
    data = response.json()
    print(data.keys())  # Print the keys of the JSON response
else:
    print(f"Erreur {response.status_code}: {response.text}")

dict_keys(['disruptions', 'lines', 'lastUpdatedDate'])

## **Récupérer les données présente dna sles clés API** ##

In [3]:
# Accéder aux clés des perturbations
disruptions = data.get("disruptions", [])

In [4]:
disruptions

[{'id': '74316236-8627-11ef-aca5-0a58a9feac02',
  'applicationPeriods': [{'begin': '20241012T020900',
    'end': '20241013T233400'},
   {'begin': '20241019T120900', 'end': '20241020T230900'},
   {'begin': '20241207T020900', 'end': '20241208T234400'},
   {'begin': '20250118T020900', 'end': '20250119T234900'},
   {'begin': '20250329T020900', 'end': '20250330T235400'},
   {'begin': '20250405T030400', 'end': '20250406T234900'},
   {'begin': '20250412T030400', 'end': '20250413T234900'}],
  'lastUpdate': '20250401T120646',
  'cause': 'TRAVAUX',
  'severity': 'BLOQUANTE',
  'tags': ['Actualité'],
  'title': 'Travaux boulevard Carnot et Calmette',
  'message': '<p>En raison de travaux boulevard Carnot et Calmette à Mantes-la-Jolie, les arrêts suivants ne seront pas desservis :</p><p>Ligne D : (Plaisances) Carnot reporté à Louise Michel et Calmette reporté à Mantes-la-Ville Mairie</p><p>Ligne N : Calmette et Carnot reportés à Mantes-Station</p><p>Ligne A14 : Calmette reporté à Mantes-Station</p><p>les samedis 05 et 12 avril 2025, et les dimanches 6 et 13 avril 2025</p><p>Nous vous prions de nous excuser de la gêne occasionnée.</p>'},
 {'id': '36842782-ad4d-11ef-b233-0a58a9feac02',
  'applicationPeriods': [{'begin': '20250514T220000',
    'end': '20250515T043000'},
   {'begin': '20250521T220000', 'end': '20250522T043000'}],
  'lastUpdate': '20241128T065421',
  'cause': 'TRAVAUX',
  'severity': 'BLOQUANTE',
  'tags': ['Actualité'],
  'title': 'Métro 14 : Travaux - Trafic interrompu',
  'message': "<p>Du 14 mai au 21 mai, le mercredi à partir de 22:00, le trafic sera interrompu sur l'ensemble de la ligne en raison de travaux. <br>Bus de remplacement entre Gare de Lyon et Olympiades<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"},
 {'id': '3cb5d628-ad4d-11ef-a448-0a58a9feac02',
  'applicationPeriods': [{'begin': '20250604T220000',
    'end': '20250605T043000'},
   {'begin': '20250611T220000', 'end': '20250612T043000'},
   {'begin': '20250618T220000', 'end': '20250619T043000'},
   {'begin': '20250625T220000', 'end': '20250626T043000'},
   {'begin': '20250702T220000', 'end': '20250703T043000'},
   {'begin': '20250709T220000', 'end': '20250710T043000'},
   {'begin': '20250716T220000', 'end': '20250717T043000'},
   {'begin': '20250723T220000', 'end': '20250724T043000'}],
  'lastUpdate': '20241128T065431',
  'cause': 'TRAVAUX',
  'severity': 'BLOQUANTE',
  'tags': ['Actualité'],
  'title': 'Métro 14 : Travaux - Trafic interrompu',
  'message': "<p>Du 4 juin au 23 juillet, le mercredi à partir de 22:00, le trafic sera interrompu sur l'ensemble de la ligne en raison de travaux. <br>Bus de remplacement entre Gare de Lyon et Olympiades<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"},
 {'id': 'e0812420-ad56-11ef-b233-0a58a9feac02',
  'applicationPeriods': [{'begin': '20250303T220000',
    'end': '20250304T043000'},
   {'begin': '20250304T220000', 'end': '20250305T043000'},
   {'begin': '20250310T220000', 'end': '20250311T043000'},
   {'begin': '20250311T220000', 'end': '20250312T043000'},
   {'begin': '20250317T220000', 'end': '20250318T043000'},
   {'begin': '20250318T220000', 'end': '20250319T043000'},
   {'begin': '20250324T220000', 'end': '20250325T043000'},
   {'begin': '20250325T220000', 'end': '20250326T043000'},
   {'begin': '20250331T220000', 'end': '20250401T043000'},
   {'begin': '20250401T220000', 'end': '20250402T043000'},
   {'begin': '20250407T220000', 'end': '20250408T043000'},
   {'begin': '20250408T220000', 'end': '20250409T043000'},
   {'begin': '20250414T220000', 'end': '20250415T043000'},
   {'begin': '20250415T220000', 'end': '20250416T043000'}],
  'lastUpdate': '20241128T080331',
  'cause': 'TRAVAUX',
  'severity': 'BLOQUANTE',
  'tags': ['Actualité'],
  'title': 'Métro 14 : Travaux - Trafic interrompu',
  'message': "<p>Du 3 mars au 15 avril, les lundi et mardi à partir de 22:00, le trafic sera interrompu entre Maison Blanche et Saint-Denis - Pleyel en raison de travaux. <br>Bus entre Gare de Lyon et Olympiades<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"},
 {'id': '4cd7123e-b1bb-11ef-845d-0a58a9feac02',
  'applicationPeriods': [{'begin': '20250412T044500',
    'end': '20250414T043000'}],
  'lastUpdate': '20241203T221227',
  'cause': 'TRAVAUX',
  'severity': 'BLOQUANTE',
  'tags': ['Actualité'],
  'title': 'Métro 6 : Travaux de modernisation - Trafic interrompu',
  'message': "<p>Du 12 avril au 13 avril, le trafic sera interrompu entre Nation et Daumesnil en raison de travaux de modernisation.<br>Bus de remplacement.<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"},
 {'id': '5939bd2e-b1bb-11ef-ab9b-0a58a9feac02',
  'applicationPeriods': [{'begin': '20250525T044500',
    'end': '20250526T043000'}],
  'lastUpdate': '20241203T221248',
  'cause': 'TRAVAUX',
  'severity': 'BLOQUANTE',
  'tags': ['Actualité'],
  'title': 'Métro 6 : Travaux de modernisation - Trafic interrompu',
  'message': "<p>Le 25 mai, le trafic sera interrompu entre Charles de Gaulle - Etoile et Trocadéro en direction de Nation en raison de travaux de modernisation.<br>Bus de remplacement.<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"},
 {'id': '5d2decf2-b1bb-11ef-845d-0a58a9feac02',
  'applicationPeriods': [{'begin': '20250518T044500',
    'end': '20250519T043000'}],
  'lastUpdate': '20241203T221256',
  'cause': 'TRAVAUX',
  'severity': 'BLOQUANTE',
  'tags': ['Actualité'],
  'title': 'Métro 6 : Travaux de modernisation - Trafic interrompu',
  'message': "<p>Le 18 mai, le trafic sera interrompu entre Daumesnil et Nation en raison de travaux de modernisation.<br>Bus de remplacement.<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"},
 {'id': '6190e7ea-b1bb-11ef-ab9b-0a58a9feac02',
  'applicationPeriods': [{'begin': '20250615T044500',
    'end': '20250616T043000'}],
  'lastUpdate': '20241203T221302',
  'cause': 'TRAVAUX',
  'severity': 'BLOQUANTE',
  'tags': ['Actualité'],
  'title': 'Métro 6 : Travaux de modernisation - Trafic interrompu',
  'message': "<p>Le 15 juin, le trafic sera interrompu sur l'ensemble de la ligne en raison de travaux de modernisation.<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"},
 {'id': '4a2946e2-beae-11ef-b1c7-0a58a9feac02',
  'applicationPeriods': [{'begin': '20250106T010000',
    'end': '20250606T230000'}],
  'lastUpdate': '20241220T094303',
  'cause': 'TRAVAUX',
  'severity': 'BLOQUANTE',
  'title': '4414, 4438 et TàD Etréchy, Travaux Chauffour-lès-Etréchy',
  'message': "<p>Lignes 4414, 4438 et TàD Etréchy, du 6/01/2025 au 6/06/2025, en raison de travaux à Chauffour-lès-Etréchy l'arrêt “Grande Rue” sera reporté à la sortie du village en direction de Villeconin dans les 2 sens</p>"},
 {'id': '4e10e836-cea4-11ef-bc79-0a58a9feac02',
  'applicationPeriods': [{'begin': '20250113T000000',
    'end': '20250113T235900'},
   {'begin': '20250114T000000', 'end': '20250114T235900'},
   {'begin': '20250115T000000', 'end': '20250115T235900'},
   {'begin': '20250116T000000', 'end': '20250116T235900'},
   {'begin': '20250117T000000', 'end': '20250117T235900'},
   {'begin': '20250120T000000', 'end': '20250120T235900'},
   {'begin': '20250121T000000', 'end': '20250121T235900'},
   {'begin': '20250122T000000', 'end': '20250122T235900'},
   {'begin': '20250123T000000', 'end': '20250123T235900'},
   {'begin': '20250124T000000', 'end': '20250124T235900'},
   {'begin': '20250127T000000', 'end': '20250127T235900'},
   {'begin': '20250128T000000', 'end': '20250128T235900'},
   {'begin': '20250129T000000', 'end': '20250129T235900'},
   {'begin': '20250130T000000', 'end': '20250130T235900'},
   {'begin': '20250131T000000', 'end': '20250131T235900'},
   {'begin': '20250203T000000', 'end': '20250203T235900'},
   {'begin': '20250204T000000', 'end': '20250204T235900'},
   {'begin': '20250205T000000', 'end': '20250205T235900'},
   {'begin': '20250206T000000', 'end': '20250206T235900'},
   {'begin': '20250207T000000', 'end': '20250207T235900'},
   {'begin': '20250210T000000', 'end': '20250210T235900'},
   {'begin': '20250211T000000', 'end': '20250211T235900'},
   {'begin': '20250212T000000', 'end': '20250212T235900'},
   {'begin': '20250213T000000', 'end': '20250213T235900'},
   {'begin': '20250214T000000', 'end': '20250214T235900'},
   {'begin': '20250217T000000', 'end': '20250217T235900'},
   {'begin': '20250218T000000', 'end': '20250218T235900'},
   {'begin': '20250219T000000', 'end': '20250219T235900'},
   {'begin': '20250220T000000', 'end': '20250220T235900'},
   {'begin': '20250221T000000', 'end': '20250221T235900'},
   {'begin': '20250224T000000', 'end': '20250224T235900'},
   {'begin': '20250225T000000', 'end': '20250225T235900'},
   {'begin': '20250226T000000', 'end': '20250226T235900'},
   {'begin': '20250227T000000', 'end': '20250227T235900'},
   {'begin': '20250228T000000', 'end': '20250228T235900'},
   {'begin': '20250303T000000', 'end': '20250303T235900'},
   {'begin': '20250304T000000', 'end': '20250304T235900'},
   {'begin': '20250305T000000', 'end': '20250305T235900'},
   {'begin': '20250306T000000', 'end': '20250306T235900'},
   {'begin': '20250307T000000', 'end': '20250307T235900'},
   {'begin': '20250310T000000', 'end': '20250310T235900'},
   {'begin': '20250311T000000', 'end': '20250311T235900'},
   {'begin': '20250312T000000', 'end': '20250312T235900'},
   {'begin': '20250313T000000', 'end': '20250313T235900'},
   {'begin': '20250314T000000', 'end': '20250314T235900'},
   {'begin': '20250317T000000', 'end': '20250317T235900'},
   {'begin': '20250318T000000', 'end': '20250318T235900'},
   {'begin': '20250319T000000', 'end': '20250319T235900'},
   {'begin': '20250320T000000', 'end': '20250320T235900'},
   {'begin': '20250321T000000', 'end': '20250321T235900'},
   {'begin': '20250324T000000', 'end': '20250324T235900'},
   {'begin': '20250325T000000', 'end': '20250325T235900'},
   {'begin': '20250326T000000', 'end': '20250326T235900'},
   {'begin': '20250327T000000', 'end': '20250327T235900'},
   {'begin': '20250328T000000', 'end': '20250328T235900'},
   {'begin': '20250331T000000', 'end': '20250331T235900'},
   {'begin': '20250401T000000', 'end': '20250401T235900'},
   {'begin': '20250402T000000', 'end': '20250402T235900'},
   {'begin': '20250403T000000', 'end': '20250403T235900'},
   {'begin': '20250404T000000', 'end': '20250404T235900'},
   {'begin': '20250407T000000', 'end': '20250407T235900'},
   {'begin': '20250408T000000', 'end': '20250408T235900'},
   {'begin': '20250409T000000', 'end': '20250409T235900'},
   {'begin': '20250410T000000', 'end': '20250410T235900'},
   {'begin': '20250411T000000', 'end': '20250411T235900'},
   {'begin': '20250414T000000', 'end': '20250414T235900'},
   {'begin': '20250415T000000', 'end': '20250415T235900'},
   {'begin': '20250416T000000', 'end': '20250416T235900'},
   {'begin': '20250417T000000', 'end': '20250417T235900'},
   {'begin': '20250418T000000', 'end': '20250418T235900'},
   {'begin': '20250421T000000', 'end': '20250421T235900'},
   {'begin': '20250422T000000', 'end': '20250422T235900'},
   {'begin': '20250423T000000', 'end': '20250423T235900'},
   {'begin': '20250424T000000', 'end': '20250424T235900'},
   {'begin': '20250425T000000', 'end': '20250425T235900'},
   {'begin': '20250428T000000', 'end': '20250428T235900'},
   {'begin': '20250429T000000', 'end': '20250429T235900'},
   {'begin': '20250430T000000', 'end': '20250430T235900'},
   {'begin': '20250501T000000', 'end': '20250501T235900'},
   {'begin': '20250502T000000', 'end': '20250502T235900'},
   {'begin': '20250505T000000', 'end': '20250505T235900'},
   {'begin': '20250506T000000', 'end': '20250506T235900'},
   {'begin': '20250507T000000', 'end': '20250507T235900'},
   {'begin': '20250508T000000', 'end': '20250508T235900'},
   {'begin': '20250509T000000', 'end': '20250509T235900'},
   {'begin': '20250512T000000', 'end': '20250512T235900'},
   {'begin': '20250513T000000', 'end': '20250513T235900'},
   {'begin': '20250514T000000', 'end': '20250514T235900'},
   {'begin': '20250515T000000', 'end': '20250515T235900'},
   {'begin': '20250516T000000', 'end': '20250516T235900'},
   {'begin': '20250519T000000', 'end': '20250519T235900'},
   {'begin': '20250520T000000', 'end': '20250520T235900'},
   {'begin': '20250521T000000', 'end': '20250521T235900'},
   {'begin': '20250522T000000', 'end': '20250522T235900'},
   {'begin': '20250523T000000', 'end': '20250523T235900'},
   {'begin': '20250526T000000', 'end': '20250526T235900'},
   {'begin': '20250527T000000', 'end': '20250527T235900'},
   {'begin': '20250528T000000', 'end': '20250528T235900'},
   {'begin': '20250529T000000', 'end': '20250529T235900'},
   {'begin': '20250530T000000', 'end': '20250530T235900'},
   {'begin': '20250602T000000', 'end': '20250602T235900'},
   {'begin': '20250603T000000', 'end': '20250603T235900'},
   {'begin': '20250604T000000', 'end': '20250604T235900'},
   {'begin': '20250605T000000', 'end': '20250605T235900'},
   {'begin': '20250606T000000', 'end': '20250606T235900'},
   {'begin': '20250609T000000', 'end': '20250609T235900'},
   {'begin': '20250610T000000', 'end': '20250610T235900'},
   {'begin': '20250611T000000', 'end': '20250611T235900'},
   {'begin': '20250612T000000', 'end': '20250612T235900'},
   {'begin': '20250613T000000', 'end': '20250613T235900'},
   {'begin': '20250616T000000', 'end': '20250616T235900'},
   {'begin': '20250617T000000', 'end': '20250617T235900'},
   {'begin': '20250618T000000', 'end': '20250618T235900'},
   {'begin': '20250619T000000', 'end': '20250619T235900'},
   {'begin': '20250620T000000', 'end': '20250620T235900'},
   {'begin': '20250623T000000', 'end': '20250623T235900'},
   {'begin': '20250624T000000', 'end': '20250624T235900'},
   {'begin': '20250625T000000', 'end': '20250625T235900'},
   {'begin': '20250626T000000', 'end': '20250626T235900'},
   {'begin': '20250627T000000', 'end': '20250627T235900'},
   {'begin': '20250630T000000', 'end': '20250630T235900'},
   {'begin': '20250701T000000', 'end': '20250701T235900'},
   {'begin': '20250702T000000', 'end': '20250702T235900'},
   {'begin': '20250703T000000', 'end': '20250703T235900'},
   {'begin': '20250704T000000', 'end': '20250704T235900'},
   {'begin': '20250707T000000', 'end': '20250707T235900'},
   {'begin': '20250708T000000', 'end': '20250708T235900'},
   {'begin': '20250709T000000', 'end': '20250709T235900'},
   {'begin': '20250710T000000', 'end': '20250710T235900'},
   {'begin': '20250711T000000', 'end': '20250711T235900'},
   {'begin': '20250714T000000', 'end': '20250714T235900'},
   {'begin': '20250715T000000', 'end': '20250715T235900'},
   {'begin': '20250716T000000', 'end': '20250716T235900'},
   {'begin': '20250717T000000', 'end': '20250717T235900'},
   {'begin': '20250718T000000', 'end': '20250718T235900'},
   {'begin': '20250721T000000', 'end': '20250721T235900'},
   {'begin': '20250722T000000', 'end': '20250722T235900'},
   {'begin': '20250723T000000', 'end': '20250723T235900'},
   {'begin': '20250724T000000', 'end': '20250724T235900'},
   {'begin': '20250725T000000', 'end': '20250725T235900'},
   {'begin': '20250728T000000', 'end': '20250728T235900'},
   {'begin': '20250729T000000', 'end': '20250729T235900'},
   {'begin': '20250730T000000', 'end': '20250730T235900'},
   {'begin': '20250731T000000', 'end': '20250731T235900'},
   {'begin': '20250801T000000', 'end': '20250801T235900'},
   {'begin': '20250804T000000', 'end': '20250804T235900'},
   {'begin': '20250805T000000', 'end': '20250805T235900'},
   {'begin': '20250806T000000', 'end': '20250806T235900'},
   {'begin': '20250807T000000', 'end': '20250807T235900'},
   {'begin': '20250808T000000', 'end': '20250808T235900'},
   {'begin': '20250811T000000', 'end': '20250811T235900'},
   {'begin': '20250812T000000', 'end': '20250812T235900'},
   {'begin': '20250813T000000', 'end': '20250813T235900'},
   {'begin': '20250814T000000', 'end': '20250814T235900'},
   {'begin': '20250815T000000', 'end': '20250815T235900'},
   {'begin': '20250818T000000', 'end': '20250818T235900'},
   {'begin': '20250819T000000', 'end': '20250819T235900'},
   {'begin': '20250820T000000', 'end': '20250820T235900'},
   {'begin': '20250821T000000', 'end': '20250821T235900'},
   {'begin': '20250822T000000', 'end': '20250822T235900'},
   {'begin': '20250825T000000', 'end': '20250825T235900'},
   {'begin': '20250826T000000', 'end': '20250826T235900'},
   {'begin': '20250827T000000', 'end': '20250827T235900'},
   {'begin': '20250828T000000', 'end': '20250828T235900'},
   {'begin': '20250829T000000', 'end': '20250829T235900'},
   {'begin': '20250901T000000', 'end': '20250901T235900'},
   {'begin': '20250902T000000', 'end': '20250902T235900'},
   {'begin': '20250903T000000', 'end': '20250903T235900'},
   {'begin': '20250904T000000', 'end': '20250904T235900'},
   {'begin': '20250905T000000', 'end': '20250905T235900'},
   {'begin': '20250908T000000', 'end': '20250908T235900'},
   {'begin': '20250909T000000', 'end': '20250909T235900'},
   {'begin': '20250910T000000', 'end': '20250910T235900'},
   {'begin': '20250911T000000', 'end': '20250911T235900'},
   {'begin': '20250912T000000', 'end': '20250912T235900'},
   {'begin': '20250915T000000', 'end': '20250915T235900'},
   {'begin': '20250916T000000', 'end': '20250916T235900'},
   {'begin': '20250917T000000', 'end': '20250917T235900'},
   {'begin': '20250918T000000', 'end': '20250918T235900'},
   {'begin': '20250919T000000', 'end': '20250919T235900'},
   {'begin': '20250922T000000', 'end': '20250922T235900'},
   {'begin': '20250923T000000', 'end': '20250923T235900'},
   {'begin': '20250924T000000', 'end': '20250924T235900'},
   {'begin': '20250925T000000', 'end': '20250925T235900'},
   {'begin': '20250926T000000', 'end': '20250926T235900'},
   {'begin': '20250929T000000', 'end': '20250929T235900'},
   {'begin': '20250930T000000', 'end': '20250930T235900'},
   {'begin': '20251001T000000', 'end': '20251001T235900'},
   {'begin': '20251002T000000', 'end': '20251002T235900'},
   {'begin': '20251003T000000', 'end': '20251003T235900'},
   {'begin': '20251006T000000', 'end': '20251006T235900'},
   {'begin': '20251007T000000', 'end': '20251007T235900'},
   {'begin': '20251008T000000', 'end': '20251008T235900'},
   {'begin': '20251009T000000', 'end': '20251009T235900'},
   {'begin': '20251010T000000', 'end': '20251010T235900'},
   {'begin': '20251013T000000', 'end': '20251013T235900'},
   {'begin': '20251014T000000', 'end': '20251014T235900'},
   {'begin': '20251015T000000', 'end': '20251015T235900'},
   {'begin': '20251016T000000', 'end': '20251016T235900'},
   {'begin': '20251017T000000', 'end': '20251017T235900'},
   {'begin': '20251020T000000', 'end': '20251020T235900'},
   {'begin': '20251021T000000', 'end': '20251021T235900'},
   {'begin': '20251022T000000', 'end': '20251022T235900'},
   {'begin': '20251023T000000', 'end': '20251023T235900'},
   {'begin': '20251024T000000', 'end': '20251024T235900'},
   {'begin': '20251027T000000', 'end': '20251027T235900'},
   {'begin': '20251028T000000', 'end': '20251028T235900'},
   {'begin': '20251029T000000', 'end': '20251029T235900'},
   {'begin': '20251030T000000', 'end': '20251030T235900'},
   {'begin': '20251031T000000', 'end': '20251031T235900'},
   {'begin': '20251103T000000', 'end': '20251103T235900'},
   {'begin': '20251104T000000', 'end': '20251104T235900'},
   {'begin': '20251105T000000', 'end': '20251105T235900'},
   {'begin': '20251106T000000', 'end': '20251106T235900'},
   {'begin': '20251107T000000', 'end': '20251107T235900'},
   {'begin': '20251110T000000', 'end': '20251110T235900'},
   {'begin': '20251111T000000', 'end': '20251111T235900'},
   {'begin': '20251112T000000', 'end': '20251112T235900'},
   {'begin': '20251113T000000', 'end': '20251113T235900'},
   {'begin': '20251114T000000', 'end': '20251114T235900'},
   {'begin': '20251117T000000', 'end': '20251117T235900'},

In [5]:
# Accéder aux clés des arrêts concernés
lines = data.get("lines", [])

In [6]:
lines

[{'id': 'line:IDFM:C01423',
  'name': '1',
  'shortName': '1',
  'mode': 'Bus',
  'networkId': 'network:IDFM:6',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01423',
    'name': '1',
    'disruptionIds': ['4884f0e6-00cd-11f0-af9a-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16820',
    'name': 'Rond-Point des Sciences',
    'disruptionIds': ['4884f0e6-00cd-11f0-af9a-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16819',
    'name': 'Rond-Point des Sciences',
    'disruptionIds': ['4884f0e6-00cd-11f0-af9a-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:19398',
    'name': 'Ampère',
    'disruptionIds': ['4884f0e6-00cd-11f0-af9a-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02129',
  'name': '3',
  'shortName': '3',
  'mode': 'Bus',
  'networkId': 'network:IDFM:6',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02129',
    'name': '3',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02',
     'd47a59a6-d28d-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16703',
    'name': 'Les Clos',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:479811',
    'name': 'Désiré Lefèvre',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:479806',
    'name': 'Onze Arpents',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:479809',
    'name': 'Le chat ZI',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16755',
    'name': 'Levasseur',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16704',
    'name': 'Les Clos',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:21242',
    'name': 'Onze Arpents',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:21205',
    'name': 'Le Chat ZI',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16756',
    'name': 'Levasseur',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16670',
    'name': 'Collège Maria Callas',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02137',
  'name': '4',
  'shortName': '4',
  'mode': 'Bus',
  'networkId': 'network:IDFM:6',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02137',
    'name': '4',
    'disruptionIds': ['d47a59a6-d28d-11ef-b937-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00292',
  'name': '1',
  'shortName': '1',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00292',
    'name': '1',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00324',
  'name': '1',
  'shortName': '1',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00324',
    'name': '1',
    'disruptionIds': ['df941c26-e496-11ef-a3d0-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01473',
  'name': '2',
  'shortName': '2',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01473',
    'name': '2',
    'disruptionIds': ['02ddc486-0560-11f0-8f00-0a58a9feac02',
     '6ab9bef4-f53c-11ef-b375-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01681',
  'name': '3',
  'shortName': '3',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01681',
    'name': '3',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00295',
  'name': '4',
  'shortName': '4',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00295',
    'name': '4',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02',
     '02ddc486-0560-11f0-8f00-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00308',
  'name': '6',
  'shortName': '6',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00308',
    'name': '6',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00312',
  'name': '7',
  'shortName': '7',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00312',
    'name': '7',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00297',
  'name': '8',
  'shortName': '8',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00297',
    'name': '8',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02',
     '02ddc486-0560-11f0-8f00-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00298',
  'name': '9',
  'shortName': '9',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00298',
    'name': '9',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02',
     '02ddc486-0560-11f0-8f00-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00325',
  'name': '12',
  'shortName': '12',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00325',
    'name': '12',
    'disruptionIds': ['c8cfc682-5b90-11ef-b754-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00306',
  'name': '34',
  'shortName': '34',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00306',
    'name': '34',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00310',
  'name': '502 Scolaire',
  'shortName': '502',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00310',
    'name': '502 Scolaire',
    'disruptionIds': ['9881082c-d996-11ef-aa1a-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02149',
  'name': 'B',
  'shortName': 'B',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02149',
    'name': 'B',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00332',
  'name': 'E',
  'shortName': 'E',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00332',
    'name': 'E',
    'disruptionIds': ['c8cfc682-5b90-11ef-b754-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02150',
  'name': 'F',
  'shortName': 'F',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02150',
    'name': 'F',
    'disruptionIds': ['df941c26-e496-11ef-a3d0-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00317',
  'name': 'H',
  'shortName': 'H',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00317',
    'name': 'H',
    'disruptionIds': ['42af8884-f998-11ef-b418-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00316',
  'name': 'J',
  'shortName': 'J',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00316',
    'name': 'J',
    'disruptionIds': ['42af8884-f998-11ef-b418-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00334',
  'name': 'K',
  'shortName': 'K',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00334',
    'name': 'K',
    'disruptionIds': ['09ab280c-e3bf-11ef-803f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00336',
  'name': 'M',
  'shortName': 'M',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00336',
    'name': 'M',
    'disruptionIds': ['c8cfc682-5b90-11ef-b754-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02151',
  'name': 'S5',
  'shortName': 'S5',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02151',
    'name': 'S5',
    'disruptionIds': ['09ab280c-e3bf-11ef-803f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01775',
  'name': 'S6',
  'shortName': 'S6',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01775',
    'name': 'S6',
    'disruptionIds': ['09ab280c-e3bf-11ef-803f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02677',
  'name': 'A02 Saint Denis Université',
  'shortName': 'A02 SDU',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1085',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02677',
    'name': 'A02 Saint Denis Université',
    'disruptionIds': ['2fe9811e-f264-11ee-9935-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02678',
  'name': 'A03 Paris La Défense',
  'shortName': 'A03 DEF',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1085',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02678',
    'name': 'A03 Paris La Défense',
    'disruptionIds': ['0258548c-1109-11ef-a614-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02723',
  'name': 'A04 Paris La Villette',
  'shortName': 'A04 VIL',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1085',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02723',
    'name': 'A04 Paris La Villette',
    'disruptionIds': ['a7397530-b0c3-11ef-90f2-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02679',
  'name': 'A05 Disneyland Paris',
  'shortName': 'A05 DIS',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1085',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02679',
    'name': 'A05 Disneyland Paris',
    'disruptionIds': ['a2dd0fe6-f7e2-11ee-9935-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00340',
  'name': '402',
  'shortName': '402',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1063',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00340',
    'name': '402',
    'disruptionIds': ['e4bcf98e-1466-11f0-88c2-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00345',
  'name': '408',
  'shortName': '408',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1063',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00345',
    'name': '408',
    'disruptionIds': ['9a2c4092-cf3c-11ef-b3f5-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00346',
  'name': '409',
  'shortName': '409',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1063',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00346',
    'name': '409',
    'disruptionIds': ['dd39a2a4-146e-11f0-b7af-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00342',
  'name': '412',
  'shortName': '412',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1063',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00342',
    'name': '412',
    'disruptionIds': ['570096d2-1399-11f0-bb7e-0a58a9feac02',
     '4f17c346-1399-11f0-bb7e-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:25359',
    'name': 'Petit-Châtenay',
    'disruptionIds': ['570096d2-1399-11f0-bb7e-0a58a9feac02',
     '4f17c346-1399-11f0-bb7e-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:35813',
    'name': 'Rue des Vignes',
    'disruptionIds': ['570096d2-1399-11f0-bb7e-0a58a9feac02',
     '4f17c346-1399-11f0-bb7e-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:40382',
    'name': 'Rue des Vignes',
    'disruptionIds': ['570096d2-1399-11f0-bb7e-0a58a9feac02',
     '4f17c346-1399-11f0-bb7e-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:12101',
    'name': 'Carrefour du 19 Mars 1962',
    'disruptionIds': ['570096d2-1399-11f0-bb7e-0a58a9feac02',
     '4f17c346-1399-11f0-bb7e-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01658',
  'name': '415',
  'shortName': '415',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1063',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01658',
    'name': '415',
    'disruptionIds': ['17a16e0a-d1b6-11ef-8d37-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01062',
  'name': 'Express 01',
  'shortName': '01EX',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01062',
    'name': 'Express 01',
    'disruptionIds': ['0ab46cca-1387-11f0-bb7e-0a58a9feac02',
     'f752b67a-0984-11f0-ac05-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02069',
  'name': '03A',
  'shortName': '03A',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02069',
    'name': '03A',
    'disruptionIds': ['a3b26686-1385-11f0-b7af-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02070',
  'name': '03B',
  'shortName': '03B',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02070',
    'name': '03B',
    'disruptionIds': ['6124ca8a-f426-11ef-b375-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01040',
  'name': '10',
  'shortName': '10',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01040',
    'name': '10',
    'disruptionIds': ['d15f71f0-147a-11f0-ac05-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01063',
  'name': 'Express 17',
  'shortName': '17Ex',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01063',
    'name': 'Express 17',
    'disruptionIds': ['5ab58926-1386-11f0-bb7e-0a58a9feac02',
     '6124ca8a-f426-11ef-b375-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00920',
  'name': '31',
  'shortName': '31',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00920',
    'name': '31',
    'disruptionIds': ['8d333a42-0648-11f0-afbd-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00921',
  'name': '31S',
  'shortName': '31S',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00921',
    'name': '31S',
    'disruptionIds': ['8d333a42-0648-11f0-afbd-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00922',
  'name': '32',
  'shortName': '32',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00922',
    'name': '32',
    'disruptionIds': ['95001646-0648-11f0-9201-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02160',
  'name': '32S',
  'shortName': '32S',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02160',
    'name': '32S',
    'disruptionIds': ['1d10d0ae-0b1a-11f0-8f48-0a58a9feac02',
     '95001646-0648-11f0-9201-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00923',
  'name': '33',
  'shortName': '33',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00923',
    'name': '33',
    'disruptionIds': ['1d10d0ae-0b1a-11f0-8f48-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01060',
  'name': '41A',
  'shortName': '41A',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01060',
    'name': '41A',
    'disruptionIds': ['f25a8c42-1384-11f0-b7af-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02154',
  'name': '41B',
  'shortName': '41B',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02154',
    'name': '41B',
    'disruptionIds': ['f25a8c42-1384-11f0-b7af-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01993',
  'name': '48',
  'shortName': '48',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01993',
    'name': '48',
    'disruptionIds': ['95001646-0648-11f0-9201-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00934',
  'name': '49',
  'shortName': '49',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00934',
    'name': '49',
    'disruptionIds': ['145c61f6-108f-11f0-bb7e-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00942',
  'name': '56S',
  'shortName': '56S',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00942',
    'name': '56S',
    'disruptionIds': ['1b77da0a-655a-11ef-ae41-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02035',
  'name': 'A',
  'shortName': 'A',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02035',
    'name': 'A',
    'disruptionIds': ['6124ca8a-f426-11ef-b375-0a58a9feac02',
     'c6f7cf62-13a5-11f0-b7af-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02036',
  'name': 'B',
  'shortName': 'B',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02036',
    'name': 'B',
    'disruptionIds': ['c6f7cf62-13a5-11f0-b7af-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02365',
  'name': 'Coulommiers - La Ferté Gaucher Centre',
  'shortName': 'P',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02365',
    'name': 'Coulommiers - La Ferté Gaucher Centre',
    'disruptionIds': ['1a734962-147a-11f0-ac05-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02291',
  'name': 'TàD 43',
  'shortName': 'TàD',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02291',
    'name': 'TàD 43',
    'disruptionIds': ['8f5ec8d4-39db-11ef-85e1-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00423',
  'name': '5206 (ex P)',
  'shortName': '5206',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'stop_point',
    'id': 'stop_point:IDFM:5750',
    'name': 'Place Foch',
    'disruptionIds': ['ff5f1896-d80a-11ef-b2cf-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00168',
  'name': '5208 (ex 8)',
  'shortName': '5208',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00168',
    'name': '5208 (ex 8)',
    'disruptionIds': ['9b4c0afe-04be-11f0-8747-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00414',
  'name': '5214 (ex Q)',
  'shortName': '5214',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'stop_point',
    'id': 'stop_point:IDFM:5750',
    'name': 'Place Foch',
    'disruptionIds': ['ff5f1896-d80a-11ef-b2cf-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00422',
  'name': '5219 (ex V)',
  'shortName': '5219',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'stop_point',
    'id': 'stop_point:IDFM:5750',
    'name': 'Place Foch',
    'disruptionIds': ['ff5f1896-d80a-11ef-b2cf-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00177',
  'name': '5224 (ex 24)',
  'shortName': '5224',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00177',
    'name': '5224 (ex 24)',
    'disruptionIds': ['3c7bb8b0-0024-11f0-829f-0a58a9feac02',
     '9b4c0afe-04be-11f0-8747-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00181',
  'name': '5230 (ex 30)',
  'shortName': '5230',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00181',
    'name': '5230 (ex 30)',
    'disruptionIds': ['9b4c0afe-04be-11f0-8747-0a58a9feac02',
     'c236f894-0ec9-11f0-88c2-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00517',
  'name': '5281 (ex 39-30D)',
  'shortName': '5281',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00517',
    'name': '5281 (ex 39-30D)',
    'disruptionIds': ['b0dc7026-1453-11f0-ac05-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01874',
  'name': '5288 (ex FA)',
  'shortName': '5288',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01874',

## **Convertir les data de la clé diruption en Dataframe** ##

In [7]:
pd.reset_option('display.max_colwidth')

# Normalisation avec l'option errors='ignore' pour ignorer les clés manquantes
df_disruptions = pd.json_normalize(data['disruptions'], 
                                  record_path='applicationPeriods', 
                                  meta=['id', 'lastUpdate', 'cause', 'severity', 'tags', 'title', 'message', 'shortMessage'], 
                                  sep=',', errors='ignore')

# Affichage du résultat
df_disruptions.head()

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage
0,20241012T020900,20241013T233400,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN
1,20241019T120900,20241020T230900,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN
2,20241207T020900,20241208T234400,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN
3,20250118T020900,20250119T234900,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN
4,20250329T020900,20250330T235400,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN

In [8]:
df_disruptions['severity'].value_counts()

severity
BLOQUANTE      3506
PERTURBEE      1638
INFORMATION     892
Name: count, dtype: int64

## **Convertir les data de la clé lines en Dataframe** ##

In [9]:
from collections import defaultdict

# 1. Créer un dictionnaire pour lier disruptionId aux arrêts concernés
disruption_to_stops = defaultdict(set)

# 2. Remplir ce dictionnaire et ajouter les informations 'name' et 'mode' à chaque disruptionId
disruption_line_info = {}  # Dictionnaire pour lier disruptionId aux informations de ligne (name, mode)

for line in lines:
    for obj in line.get('impactedObjects', []):
        if obj['type'] == 'stop_point':  # Filtrer uniquement les objets de type 'stop_point'
            stop_name = obj['name']
            for disruption_id in obj.get('disruptionIds', []):
                # Ajouter l'arrêt à la liste des arrêts pour ce disruptionId
                disruption_to_stops[disruption_id].add(stop_name)
                # Ajouter les informations de la ligne (name, mode) pour ce disruptionId
                if disruption_id not in disruption_line_info:
                    disruption_line_info[disruption_id] = {
                        'name': line['name'],
                        'mode': line['mode']
                    }

# 3. Construction du DataFrame avec les arrêts pour chaque disruptionId
df_lines = pd.DataFrame([
    {
        'disruptionId': disruption_id,
        'stop_points': sorted(list(stops)),
        'name': disruption_line_info[disruption_id]['name'],
        'mode': disruption_line_info[disruption_id]['mode'],
        
    }
    for disruption_id, stops in disruption_to_stops.items()
])

# Affichage du DataFrame final
df_lines.head()

,disruptionId,stop_points,name,mode
0,4884f0e6-00cd-11f0-af9a-0a58a9feac02,"[Ampère, Rond-Point des Sciences]",1,Bus
1,5f95054a-d707-11ef-b937-0a58a9feac02,"[Collège Maria Callas, Désiré Lefèvre, Le Chat...",3,Bus
2,570096d2-1399-11f0-bb7e-0a58a9feac02,"[Carrefour du 19 Mars 1962, Petit-Châtenay, Ru...",412,Bus
3,4f17c346-1399-11f0-bb7e-0a58a9feac02,"[Carrefour du 19 Mars 1962, Petit-Châtenay, Ru...",412,Bus
4,ff5f1896-d80a-11ef-b2cf-0a58a9feac02,"[Place Foch, Rue Andin]",5206 (ex P),Bus

## **Filtrer évènements en cours du dataset disruptions** ##

In [10]:
from datetime import datetime

def filtrer_evenements_en_cours(df, col_debut="begin", col_fin="end", now=None):
    """
    Filtre les événements en cours à partir d'un DataFrame avec colonnes 'start' et 'end' (format 'YYYYMMDDTHHMMSS').

    :param df: DataFrame contenant les événements
    :param col_debut: nom de la colonne de début (par défaut "start")
    :param col_fin: nom de la colonne de fin (par défaut "end")
    :param now: datetime personnalisé (utile pour les tests), sinon datetime.now()
    :return: DataFrame filtré avec les événements en cours
    """
    df = df.copy()
    
    # Conversion des dates
    df[col_debut] = pd.to_datetime(df[col_debut], format="%Y%m%dT%H%M%S", errors='coerce')
    df[col_fin] = pd.to_datetime(df[col_fin], format="%Y%m%dT%H%M%S", errors='coerce')

    # Date/heure actuelle
    now = now or pd.Timestamp.now()

    # Filtrage des événements en cours
    df_current = df[(df[col_debut] <= now) & (df[col_fin] >= now)]
    
    return df_current

In [11]:
df_current = filtrer_evenements_en_cours(df_disruptions)
df_current.head(2)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage
35,2025-01-06 01:00:00,2025-06-06 23:00:00,4a2946e2-beae-11ef-b1c7-0a58a9feac02,20241220T094303,TRAVAUX,BLOQUANTE,NaN,"4414, 4438 et TàD Etréchy, Travaux Chauffour-l...","<p>Lignes 4414, 4438 et TàD Etréchy, du 6/01/2...",NaN
97,2025-04-08 00:00:00,2025-04-08 23:59:00,4e10e836-cea4-11ef-bc79-0a58a9feac02,20250228T154728,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,<p>En raison de travaux avenue Jean Jaurès à M...,NaN

In [12]:
def filtrer_evenements_previsionnels(df, col_debut="begin", col_fin="end", now=None):
    """
    Filtre les événements dont le début est dans les 2 heures à venir.

    :param df: DataFrame contenant les événements
    :param col_debut: nom de la colonne de début
    :param col_fin: nom de la colonne de fin
    :param now: datetime personnalisé (utile pour les tests), sinon datetime.now()
    :return: DataFrame filtré avec les événements débutant dans les 2 prochaines heures
    """
    df = df.copy()
    
    # Conversion des dates
    df[col_debut] = pd.to_datetime(df[col_debut], format="%Y%m%dT%H%M%S", errors='coerce')
    df[col_fin] = pd.to_datetime(df[col_fin], format="%Y%m%dT%H%M%S", errors='coerce')

    # Date/heure actuelle
    now = now or pd.Timestamp.now()
    dans_2h = now + pd.Timedelta(hours=7)

    # Filtrage des événements qui commenceront dans les 2 prochaines heures
    df_preview = df[(df[col_debut] >= now) & (df[col_debut] <= dans_2h)]

    return df_preview

In [13]:
df_preview = filtrer_evenements_previsionnels(df_disruptions)
df_preview.head(2)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage
28,2025-04-08 22:00:00,2025-04-09 04:30:00,e0812420-ad56-11ef-b233-0a58a9feac02,20241128T080331,TRAVAUX,BLOQUANTE,[Actualité],Métro 14 : Travaux - Trafic interrompu,"<p>Du 3 mars au 15 avril, les lundi et mardi à...",NaN
653,2025-04-08 22:00:00,2025-04-09 04:30:00,9b41a11c-f90c-11ef-af9a-0a58a9feac02,20250305T105203,TRAVAUX,BLOQUANTE,[Actualité],Ligne 480 (Seine Grand Orly) - Arrêt Orly 4 no...,<p><strong><u>Ligne 480 (Seine Grand Orly) - A...,NaN

## **Merged dataset disruptions et lines sur les clés communes disruptionId et id** ##

In [14]:
# On renomme "disruptionId" en "id" dans df_lines pour pouvoir faire la jointure facilement
df_lines_renamed = df_lines.rename(columns={'disruptionId': 'id'})

# Merge (left join) : on garde tout df_en_cours, et on ajoute les colonnes de df_lines si id commun
df_current_merged = df_current.merge(df_lines_renamed, on='id', how='left')

In [15]:
# Merge (left join) : on garde tout df_en_cours, et on ajoute les colonnes de df_lines si id commun
df_preview_merged = df_preview.merge(df_lines_renamed, on='id', how='left')

## **PREPROCESSING** ##

In [16]:
from bs4 import BeautifulSoup
# Supprimer valeurs NAN et converttir en str
df_current_merged['message'] = df_current_merged['message'].astype(str).fillna('')

# Appliquer la suppression des balises HTML à chaque message de la colonne 'message'
df_current_merged['message'] = df_current_merged['message'].apply(
    lambda msg: BeautifulSoup(msg, "html.parser").get_text()
)

In [17]:
# Supprimer valeurs NAN et converttir en str
df_preview_merged['message'] = df_preview_merged['message'].astype(str).fillna('')

# Appliquer la suppression des balises HTML à chaque message de la colonne 'message'
df_preview_merged['message'] = df_preview_merged['message'].apply(
    lambda msg: BeautifulSoup(msg, "html.parser").get_text()
)

In [18]:
df_current_merged.head(2)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode
0,2025-01-06 01:00:00,2025-06-06 23:00:00,4a2946e2-beae-11ef-b1c7-0a58a9feac02,20241220T094303,TRAVAUX,BLOQUANTE,NaN,"4414, 4438 et TàD Etréchy, Travaux Chauffour-l...","Lignes 4414, 4438 et TàD Etréchy, du 6/01/2025...",NaN,[Grande Rue],4414,Bus
1,2025-04-08 00:00:00,2025-04-08 23:59:00,4e10e836-cea4-11ef-bc79-0a58a9feac02,20250228T154728,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,En raison de travaux avenue Jean Jaurès à Mant...,NaN,"[Louise Michel, Mantes Station, Mantes-la-Vill...",88C,Bus

In [19]:
df_preview_merged

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode
0,2025-04-08 22:00:00,2025-04-09 04:30:00,e0812420-ad56-11ef-b233-0a58a9feac02,20241128T080331,TRAVAUX,BLOQUANTE,[Actualité],Métro 14 : Travaux - Trafic interrompu,"Du 3 mars au 15 avril, les lundi et mardi à pa...",NaN,"[Bercy, Bibliothèque François Mitterrand, Chât...",14,Metro
1,2025-04-08 22:00:00,2025-04-09 04:30:00,9b41a11c-f90c-11ef-af9a-0a58a9feac02,20250305T105203,TRAVAUX,BLOQUANTE,[Actualité],Ligne 480 (Seine Grand Orly) - Arrêt Orly 4 no...,Ligne 480 (Seine Grand Orly) - Arrêt non desse...,NaN,[Aéroport Orly 4],480,Bus
2,2025-04-08 22:00:00,2025-04-09 04:30:00,640bcc8c-043c-11f0-9201-0a58a9feac02,20250318T220307,TRAVAUX,BLOQUANTE,[Actualité],Métro 10 : Travaux - Trafic interrompu,"Jusqu'au 29 avril (sauf le 9 avril), du lundi ...",Trafic interrompu,NaN,NaN,NaN
3,2025-04-08 22:45:00,2025-04-09 02:45:00,e5f599c4-0632-11f0-9201-0a58a9feac02,20250321T100012,TRAVAUX,BLOQUANTE,[Actualité],Ligne B : Châtelet - CDG2/Mitry du 31/03 au 25/04,"Période : du lundi au vendredi, à partir de 22...",Trafic interrompu planifié,"[Antony, Arcueil - Cachan, Aulnay-sous-Bois, A...",B,RapidTransit
4,2025-04-08 22:00:00,2025-04-09 04:30:00,4e42f940-0f34-11f0-8f48-0a58a9feac02,20250401T220258,TRAVAUX,BLOQUANTE,[Actualité],Métro 14 : Travaux - Trafic interrompu,"Jusqu'au 29 avril, les lundi et mardi à partir...",Trafic interrompu,"[Bercy, Bibliothèque François Mitterrand, Chât...",14,Metro
5,2025-04-08 22:30:00,2025-04-08 23:30:00,ff978aca-13b3-11f0-b7af-0a58a9feac02,20250407T152710,TRAVAUX,BLOQUANTE,[Actualité],Ligne D : Paris Lyon<>Villeneuve : du 31/03 au...,Période : à partir de 22h30.Date : lundi 31 ma...,Arrêts non desservis planifiés,"[Ballancourt, Boigneville, Boussy-Saint-Antoin...",D,RapidTransit
6,2025-04-08 21:00:00,2025-04-09 02:40:00,e55e5334-141f-11f0-8f48-0a58a9feac02,20250408T041927,TRAVAUX,BLOQUANTE,NaN,Bus 112 : Travaux - Arrêt(s) non desservi(s),La ligne 112 sera déviée : les arrêts situés e...,Arrêt(s) non desservi(s),"[Carrefour de Beauté, Cartoucherie, Champ de M...",112,Bus
7,2025-04-08 21:00:00,2025-04-09 02:40:00,ec9e5a2c-141f-11f0-88c2-0a58a9feac02,20250408T041941,TRAVAUX,BLOQUANTE,NaN,Bus 112 : Travaux - Arrêt(s) non desservi(s),La ligne 112 sera déviée : les arrêts situés e...,Arrêt(s) non desservi(s),"[Carrefour de Beauté, Cartoucherie, Champ de M...",112,Bus
8,2025-04-08 20:00:00,2025-04-09 03:00:00,1a79691c-1422-11f0-bb7e-0a58a9feac02,20250408T043515,PERTURBATION,BLOQUANTE,NaN,Bus 235 : Incident sur la voie publique - Arrê...,La ligne 235 sera déviée : les arrêts situés e...,Arrêt(s) non desservi(s),"[Cité du Luth-Verlaine, Deslandes, Le Luth, Le...",235,Bus
9,2025-04-08 20:00:00,2025-04-09 03:00:00,23bf9334-1422-11f0-88c2-0a58a9feac02,20250408T043531,PERTURBATION,BLOQUANTE,NaN,Bus 235 : Incident sur la voie publique - Arrê...,La ligne 235 sera déviée : les arrêts situés e...,Arrêt(s) non desservi(s),"[Cité du Luth-Verlaine, Deslandes, Le Luth, Le...",235,Bus
10,2025-04-08 22:30:00,2025-04-09 03:00:00,60941bf4-1468-11f0-b7af-0a58a9feac02,20250408T125818,TRAVAUX,BLOQUANTE,NaN,Bus 68 : Travaux - Arrêt(s) non desservi(s),L'arrêt Pyramides - Saint-Honoré de la ligne 6...,Arrêt(s) non desservi(s),"[Pont Royal - Quai Voltaire, Pyramides, Pyrami...",68,Bus
11,2025-04-08 22:00:00,2025-04-09 04:30:00,f5d79d4e-146d-11f0-ac05-0a58a9feac02,20250408T133815,TRAVAUX,BLOQUANTE,NaN,Bus 183 : Travaux - Arrêt(s) non desservi(s),L'arrêt Aéroport d'Orly 4 de la ligne 183 ne s...,Arrêt(s) non desservi(s),"[Aéroport Orly 1-2-3, Aéroport Orly 4, Coeur d...",183,Bus
12,2025-04-08 22:30:00,2025-04-09 02:30:00,8f621c66-1471-11f0-8f48-0a58a9feac02,20250408T140402,TRAVAUX,BLOQUANTE,[Actualité],ligne D : arrêt non désservis,Période : dès 22h30. Dates : du lundi 28 Avril...,Arrêt non desservi planifié,"[Ballancourt, Boigneville, Boussy-Saint-Antoin...",D,RapidTransit
13,2025-04-08 21:00:00,2025-04-09 02:50:00,cc4831d8-1476-11f0-b7af-0a58a9feac02,20250408T144131,TRAVAUX,BLOQUANTE,[Actualité],Ligne T13 : St Germain <> St Cyr du 01/04 au 2...,"Dates : du 01/04 au 25/04, en semaine du lundi...",Trafic interrompu planifié,NaN,NaN,NaN
14,2025-04-08 19:30:00,2025-04-08 20:30:00,b9d459b6-ed0f-11ef-831e-0a58a9feac02,20250217T101526,TRAVAUX,PERTURBEE,[Actualité],Ligne E : Nanterre - Tournan 7 - 11/04,Dates : du lundi 7 au vendredi 11 avrilL'horai...,trafic ralenti,"[Gretz-Armainvilliers, Haussmann Saint-Lazare,...",E,RapidTransit
15,2025-04-08 22:20:00,2025-04-09 02:50:00,638911b8-f29c-11ef-b375-0a58a9feac02,20250224T114457,TRAVAUX,PERTURBEE,[Actualité],Ligne P : Paris Est - Meaux 31/03 - 30/05,Période : à partir de 22h20 Dates : du lundi 3...,trafic ralenti,NaN,NaN,NaN
16,2025-04-08 22:00:00,2025-04-09 02:30:00,a8ad5934-f29c-11ef-96bd-0a58a9feac02,20250224T114653,TRAVAUX,PERTURBEE,[Actualité],Ligne P : Paris Est - Château-Thierry 31/03-30/05,Période : à partir de 22h00 Dates : du lundi 3...,trafic ralenti,NaN,NaN,NaN
17,2025-04-08 21:45:00,2025-04-09 00:00:00,ecb1f326-f2b3-11ef-b375-0a58a9feac02,20250224T143325,TRAVAUX,PERTURBEE,[Actualité],Ligne P : Paris Est - Provins 31/03 - 16/05,Période : à partir de 21h45Dates : du lundi 31...,trafic ralenti,NaN,NaN,NaN
18,2025-04-08 22:40:00,2025-04-09 01:50:00,a93f8438-f37f-11ef-b418-0a58a9feac02,20250225T145149,TRAVAUX,PERTURBEE,[Actualité],Ligne E : Nanterre - Chelles 7/04 - 9/X05,Période : à partir de 22h45 Dates : du lundi 7...,trafic ralenti,"[Bondy, Chelles - Gournay, Gagny, Haussmann Sa...",E,RapidTransit
19,2025-04-08 22:40:00,2025-04-09 01:50:00,b1a004b8-f37f-11ef-96bd-0a58a9feac02,20250225T145203,TRAVAUX,PERTURBEE,[Actualité],Ligne E : Nanterre - Chelles 7/04 - 9/05,Période : à partir de 22h45 Dates : du lundi 7...,trafic ralenti,"[Bondy, Chelles - Gournay, Gagny, Haussmann Sa...",E,RapidTransit
20,2025-04-08 22:40:00,2025-04-09 03:00:00,c85f667c-f676-11ef-96bd-0a58a9feac02,20250301T092550,TRAVAUX,PERTURBEE,[Actualité],Ligne J : Argenteuil - Pontoise/Mantes 31/03-1...,Période : à partir de 21h00 Dates : du lundi ...,Trafic interrompu planifié,NaN,NaN,NaN
21,2025-04-08 21:55:00,2025-04-09 02:59:00,212f0f32-f816-11ef-b418-0a58a9feac02,20250303T105900,TRAVAUX,PERTURBEE,[Actualité],Ligne N : Paris M - Plaisir - G du 22/04 au 02/05,"Période : du lundi au vendredi, le soir à part...",Trafic interrompu planifié,"[Chaville Rive Gauche, Clamart, Fontenay-le-Fl...",N,LocalTrain
22,2025-04-08 22:50:00,2025-04-09 03:00:00,35445162-f816-11ef-96bd-0a58a9feac02,20250303T105933,TRAVAUX,PERTURBEE,[Actualité],L : Paris-Nanterre U./Maisons-Laffitte 31/03-1...,Période : à partir de 22h00 Dates : du lundi 3...,Trafic interrompu planifié,NaN,NaN,NaN
23,2025-04-08 21:00:00,2025-04-09 02:59:00,0dd19ac4-f819-11ef-af9a-0a58a9feac02,20250303T111956,TRAVAUX,PERTURBEE,[Actualité],Ligne N : Paris Montp. - Dreux du 07/04 au 02/05.,"Période : du lundi au vendredi, le soir à part...",Trafic interrompu planifié,"[Chaville Rive Gauche, Clamart, Dreux, Fontena...",N,LocalTrain
24,2025-04-08 20:30:00,2025-04-09 02:59:00,42ffa48e-f81e-11ef-96bd-0a58a9feac02,20250303T115713,TRAVAUX,PERTURBEE,[Actualité],Ligne U: La Verrière -La Défense du 07/04 au 1...,"Période : du lundi au vendredi, le soir à part...",Trafic interrompu planifié,NaN,NaN,NaN
25,2025-04-08 20:40:00,2025-04-08 21:20:00,97c3dd3e-0591-11f0-949f-0a58a9feac02,20250320T144532,TRAVAUX,PERTURBEE,[Actualité],Ligne E : Villiers - Nanterre 7/04 - 9/05,Dates : du lundi 7 avril au vendredi 9 mai sau...,trafic ralenti,"[Haussmann Saint-Lazare, La Défense, Les Boull...",E,RapidTransit
26,2025-04-08 22:10:00,2025-04-09 01:20:00,299fc9e8-0592-11f0-949f-0a58a9feac02,20250320T144937,TRAVAUX,PERTURBEE,[Actualité],Ligne P : Paris Est - Coulommiers 31/03 - 16/05,Période : à partir de 22h15 Dates : du lundi ...,trafic ralenti,NaN,NaN,NaN
27,2025-04-08 22:25:00,2025-04-09 02:15:00,c09a4562-088a-11f0-afbd-0a58a9feac02,20250324T093411,TRAVAUX,PERTURBEE,[Actualité],Ligne E : Nanterre - Villiers/Tournan 7/04 - 1...,Période : à partir de 22h25 \n\nDates : du lun...,trafic ralenti,"[Gretz-Armainvilliers, Haussmann Saint-Lazare,...",E,RapidTransit

In [20]:
# Récupérer les ID des perturbations du précédent appel API
# Par exemple, ces ID pourraient être stockés dans un fichier ou une base de données.
previous_disruptions = set(df_current_merged['id'].tolist())

# Simulons un nouvel appel API en modifiant df_merged pour représenter le nouvel état des perturbations
# Ce dataframe (df_merged) serait mis à jour à chaque appel API avec de nouvelles données.
new_disruptions = set(df_current_merged['id'].tolist())  # Ici on reprend la même liste, mais dans un vrai cas, ce serait mis à jour.

# Ajouter la colonne 'status' en fonction des conditions
df_current_merged['status'] = df_current_merged['id'].apply(
    lambda x: 'new' if x not in previous_disruptions else ('finished' if x not in new_disruptions else 'now')
)

# Afficher le DataFrame avec la nouvelle colonne 'status'
df_current_merged.head()

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode,status
0,2025-01-06 01:00:00,2025-06-06 23:00:00,4a2946e2-beae-11ef-b1c7-0a58a9feac02,20241220T094303,TRAVAUX,BLOQUANTE,NaN,"4414, 4438 et TàD Etréchy, Travaux Chauffour-l...","Lignes 4414, 4438 et TàD Etréchy, du 6/01/2025...",NaN,[Grande Rue],4414,Bus,now
1,2025-04-08 00:00:00,2025-04-08 23:59:00,4e10e836-cea4-11ef-bc79-0a58a9feac02,20250228T154728,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,En raison de travaux avenue Jean Jaurès à Mant...,NaN,"[Louise Michel, Mantes Station, Mantes-la-Vill...",88C,Bus,now
2,2025-04-08 00:00:00,2025-04-08 23:59:00,0bbdedb6-cea5-11ef-b1c7-0a58a9feac02,20250218T162628,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,En raison de travaux avenue Jean Jaurès à Mant...,NaN,NaN,NaN,NaN,now
3,2025-01-13 00:00:00,2025-12-31 23:59:00,30376efa-cea6-11ef-8d37-0a58a9feac02,20250109T172424,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,En raison de travaux avenue Jean Jaurès à Mant...,NaN,[Poste],21,Bus,now
4,2025-01-13 00:00:00,2025-06-30 23:59:00,426b148c-ceab-11ef-8d37-0a58a9feac02,20250313T203153,TRAVAUX,BLOQUANTE,NaN,🚧 5121 5152 - Travaux : Arrêt Golf National da...,🚧 #Perturbations #Ligne5121 #Ligne5152📅 à part...,NaN,[Golf National],5121,Bus,now

## **Ouvrir le précédent appel API s'il existe** ##

In [21]:
# Charger le fichier CSV de la version précédente
historic_api_file = "df_previous_merged.csv"

try:
    df_previous = pd.read_csv(historic_api_file)
    print("Fichier précédent chargé depuis CSV.")
except FileNotFoundError:
    df_previous = pd.DataFrame(columns=["id", "name", "mode", "begin", "end", "severity", "tags", "title", "message", "status"])
    print("Aucun fichier précédent trouvé, c’est le premier appel ?")

Fichier précédent chargé depuis CSV.

## **Remplacer l'ancien appel API par l'actuel qui deviendra lui même l'ancien appel API** ##

In [22]:
df_current_merged.to_csv(f"df_previous_merged.csv", index=False)

In [23]:
df_current = df_current_merged

## **Mise à jour du statut des disruptions : nouvelles, en cours, terminées** ##

In [24]:
# Ajouter la colonne 'status' pour les disruptions actuelles
df_current["status"] = df_current["id"].apply(
    lambda x: "new" if x not in df_previous["id"].values else "now"
)

# Identifier les disruptions terminées ("finished")
finished_ids = set(df_previous["id"]) - set(df_current["id"])
df_finished = df_previous[df_previous["id"].isin(finished_ids)].copy()
df_finished["status"] = "finished"  # Ajouter le statut "finished"

## **Concaténer les résultats** ##

In [25]:
# Fusionner les disruptions actuelles et terminées
df_current_histo = pd.concat([df_current, df_finished], ignore_index=True)

In [26]:
df_current_histo.head(3)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode,status
0,2025-01-06 01:00:00,2025-06-06 23:00:00,4a2946e2-beae-11ef-b1c7-0a58a9feac02,20241220T094303,TRAVAUX,BLOQUANTE,NaN,"4414, 4438 et TàD Etréchy, Travaux Chauffour-l...","Lignes 4414, 4438 et TàD Etréchy, du 6/01/2025...",NaN,[Grande Rue],4414,Bus,now
1,2025-04-08 00:00:00,2025-04-08 23:59:00,4e10e836-cea4-11ef-bc79-0a58a9feac02,20250228T154728,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,En raison de travaux avenue Jean Jaurès à Mant...,NaN,"[Louise Michel, Mantes Station, Mantes-la-Vill...",88C,Bus,now
2,2025-04-08 00:00:00,2025-04-08 23:59:00,0bbdedb6-cea5-11ef-b1c7-0a58a9feac02,20250218T162628,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,En raison de travaux avenue Jean Jaurès à Mant...,NaN,NaN,NaN,NaN,now

In [27]:
df_current_histo['mode'].value_counts()

mode
Bus             280
RapidTransit      6
LocalTrain        3
Tramway           1
Metro             1
Name: count, dtype: int64

## **Filtrer les disruptions concernant le réseau férré** ##

In [28]:
df_current_filtered = df_current_histo[df_current_histo['mode'].isin(['RapidTransit', 'LocalTrain', 'Tramway', 'Metro'])]

In [29]:
df_preview_filtered = df_preview_merged[df_preview_merged['mode'].isin(['RapidTransit', 'LocalTrain', 'Tramway', 'Metro'])]

In [30]:
df_preview_filtered.shape

(12, 13)

In [31]:
df_preview_filtered.head(3)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode
0,2025-04-08 22:00:00,2025-04-09 04:30:00,e0812420-ad56-11ef-b233-0a58a9feac02,20241128T080331,TRAVAUX,BLOQUANTE,[Actualité],Métro 14 : Travaux - Trafic interrompu,"Du 3 mars au 15 avril, les lundi et mardi à pa...",NaN,"[Bercy, Bibliothèque François Mitterrand, Chât...",14,Metro
3,2025-04-08 22:45:00,2025-04-09 02:45:00,e5f599c4-0632-11f0-9201-0a58a9feac02,20250321T100012,TRAVAUX,BLOQUANTE,[Actualité],Ligne B : Châtelet - CDG2/Mitry du 31/03 au 25/04,"Période : du lundi au vendredi, à partir de 22...",Trafic interrompu planifié,"[Antony, Arcueil - Cachan, Aulnay-sous-Bois, A...",B,RapidTransit
4,2025-04-08 22:00:00,2025-04-09 04:30:00,4e42f940-0f34-11f0-8f48-0a58a9feac02,20250401T220258,TRAVAUX,BLOQUANTE,[Actualité],Métro 14 : Travaux - Trafic interrompu,"Jusqu'au 29 avril, les lundi et mardi à partir...",Trafic interrompu,"[Bercy, Bibliothèque François Mitterrand, Chât...",14,Metro

In [32]:
df_current_filtered.shape

(11, 14)

In [33]:
df_current_filtered['status'].value_counts()

status
finished    5
now         4
new         2
Name: count, dtype: int64

In [34]:
df_current_filtered.head(3)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode,status
60,2025-03-27 18:42:00,2025-04-22 04:30:00,26847bb8-0b33-11f0-b7af-0a58a9feac02,20250327T184436,TRAVAUX,BLOQUANTE,[Actualité],Tramway T1 : Travaux - Trafic interrompu,"Jusqu'au lundi 21 avril 2025, le trafic est in...",Trafic interrompu,"[Auguste Delaune, Bobigny - Pablo Picasso, Esc...",T1,Tramway,now
316,2025-04-08 08:15:00,2025-04-08 16:20:00,99c8f304-f2c1-11ef-96bd-0a58a9feac02,20250224T161119,TRAVAUX,PERTURBEE,[Actualité],Ligne E : Nanterre- Chelles 7 - 11/04,Période : de 8h15 à 16h15Dates : du lundi 7 au...,trafic ralenti,"[Bondy, Chelles - Gournay, Gagny, Haussmann Sa...",E,RapidTransit,now
367,2025-04-08 09:00:00,2025-04-08 16:00:00,97f26936-0ed5-11f0-ac05-0a58a9feac02,20250401T104458,TRAVAUX,PERTURBEE,[Actualité],Ligne D Goussainville Melun 03 mars au 22 août...,Période : de 09h00 à 16h00.Dates : du lundi 3 ...,trafic ralenti,"[Boussy-Saint-Antoine, Brunoy, Châtelet les Ha...",D,RapidTransit,now

In [35]:
# CALL API
API_KEY = "haj00y9FzSQ1VZCTUjpmla8Q98xRnA6a"

URL = 'https://prim.iledefrance-mobilites.fr/marketplace/v2/navitia/line_reports/line_reports'

headers = {
    "Accept": "application/json",
    "apikey": API_KEY
}

response = requests.get(URL, headers=headers)

if response.status_code == 200:
    data_2 = response.json()
    print(data.keys())
else:
    print(f"Erreur {response.status_code}: {response.text}")

dict_keys(['disruptions', 'lines', 'lastUpdatedDate'])

In [36]:
disruptions_pag_v2 = data_2.get("pagination", [])

In [37]:
disruptions_pag_v2

{'total_result': 863,
 'start_page': 0,
 'items_per_page': 25,
 'items_on_page': 25}

In [38]:
# Accéder aux clés des perturbations
disruptions_v2 = data_2.get("disruptions", [])

In [39]:
disruptions_v2

[{'id': '5f95054a-d707-11ef-b937-0a58a9feac02',
  'disruption_id': 'b0e9ae60-d3f0-11ef-aa1a-0a58a9feac02',
  'impact_id': '5f95054a-d707-11ef-b937-0a58a9feac02',
  'application_periods': [{'begin': '20250120T040000',
    'end': '20250530T230000'}],
  'status': 'active',
  'updated_at': '20250226T152150',
  'cause': 'travaux',
  'category': 'Incidents',
  'severity': {'name': 'Bloquante passante',
   'effect': 'MODIFIED_SERVICE',
   'color': '#FF0000',
   'priority': 0},
  'messages': [{'text': '<p>En raison de travaux, avenue de Chantereine, une déviation doit être mise en place.&nbsp;<br>Du lundi 20 janvier au vendredi 30 mai 2025.<br>- En direction de la Gare de Chelles : les arrêts Collège Maria Callas, Le Chat ZI, Onze Arpents, Désiré Lefèvre, Les Clos, Levasseur ne seront pas desservis.&nbsp;<br>Merci de vous reporter aux arrêts La Régale (poteau ligne 5 direction Gare de Lagny-Thorigny), ou Chantereine.&nbsp;<br>- En direction de la Gare de Villeparisis / Eglise de Courtry : les arrêts Les Clos, Levasseur, Désiré Lefèvre, Onze Arpents, Le Chat ZI ne seront pas desservis.&nbsp;<br>Merci de vous reporter aux arrêts Chantereine, La Régale (poteau Ligne 5 direction Hôpital de Montfermeil) ou Collège Maria Callas<br>Nous vous prions de bien vouloir nous excuser pour la gêne occasionnée.</p>',
    'channel': {'content_type': 'text/html',
     'id': '3ae8df3e-7488-11e8-ac3b-005056a47b86',
     'name': 'moteur',
     'types': ['web']}},
   {'text': 'Transdev STBC- Ligne 3 - Travaux Av de Chantereine',
    'channel': {'content_type': 'text/plain',
     'id': 'd9dbc5a6-7a06-11e8-8b8c-005056a44da2',
     'name': 'titre',
     'types': ['title']}}],
  'impacted_objects': [{'pt_object': {'id': 'line:IDFM:C02129',
     'name': 'Apolo 7 Bus 3',
     'quality': 0,
     'line': {'id': 'line:IDFM:C02129',
      'name': '3',
      'code': '3',
      'color': 'B44A9C',
      'text_color': 'FFFFFF',
      'codes': [{'type': 'Netex_PrivateCode', 'value': '101361013'},
       {'type': 'source', 'value': 'FR1:Line:C02129:'}],
      'physical_modes': [{'id': 'physical_mode:Bus', 'name': 'Bus'}],
      'commercial_mode': {'id': 'commercial_mode:Bus', 'name': 'Bus'},
      'network': {'id': 'network:IDFM:6',
       'name': 'Apolo 7',
       'links': [],
       'codes': [{'type': 'source', 'value': 'FR1:Network:6:LOC'}]},
      'opening_time': '052000',
      'closing_time': '220800',
      'geojson': {'type': 'MultiLineString', 'coordinates': []},
      'links': []},
     'embedded_type': 'line'},
    'impacted_section': {'from': {'id': 'stop_area:IDFM:68646',
      'name': 'Les Clos (Chelles)',
      'quality': 0,
      'stop_area': {'id': 'stop_area:IDFM:68646',
       'name': 'Les Clos',
       'codes': [{'type': 'source',
         'value': 'FR::multimodalStopPlace:68646:FR1'}],
       'timezone': 'Europe/Paris',
       'label': 'Les Clos (Chelles)',
       'coord': {'lon': '2.610341', 'lat': '48.903334'},
       'links': []},
      'embedded_type': 'stop_area'},
     'to': {'id': 'stop_area:IDFM:461884',
      'name': 'Le Chat ZI (Courtry)',
      'quality': 0,
      'stop_area': {'id': 'stop_area:IDFM:461884',
       'name': 'Le Chat ZI',
       'codes': [{'type': 'source',
         'value': 'FR::multimodalStopPlace:461884:FR1'}],
       'timezone': 'Europe/Paris',
       'label': 'Le Chat ZI (Courtry)',
       'coord': {'lon': '2.602243', 'lat': '48.908838'},
       'links': []},
      'embedded_type': 'stop_area'},
     'routes': [{'id': 'route:IDFM:STBC:29796-C02129-4044-ALLER',
       'name': 'Gare de Villeparisis Mitry-le-Neuf',
       'is_frequence': 'False',
       'direction_type': 'inbound',
       'codes': [{'type': 'Netex_ServiceJourneyPattern',
         'value': 'STBC:ServiceJourneyPattern:29796-C02129-37377:LOC'},
        {'type': 'Netex_ServiceJourneyPattern',
         'value': 'STBC:ServiceJourneyPattern:29796-C02129-37378:LOC'},
        {'type': 'source', 'value': 'STBC:Route:29796-C02129-4044-ALLER:LOC'}],
       'direction': {'id': 'stop_area:IDFM:68916',
        'name': 'Villeparisis - Mitry-le-Neuf (Mitry-Mory)',
        'quality': 0,
        'stop_area': {'id': 'stop_area:IDFM:68916',
         'name': 'Villeparisis - Mitry-le-Neuf',
         'codes': [{'type': 'TN_PA', 'value': '79'},
          {'type': 'source', 'value': 'FR::multimodalStopPlace:68916:FR1'}],
         'timezone': 'Europe/Paris',
         'label': 'Villeparisis - Mitry-le-Neuf (Mitry-Mory)',
         'coord': {'lon': '2.602796', 'lat': '48.953516'},
         'links': []},
        'embedded_type': 'stop_area'},
       'geojson': {'type': 'MultiLineString', 'coordinates': []},
       'links': []},
      {'id': 'route:IDFM:STBC:29796-C02129-4044-RETOUR',
       'name': 'Gare de Chelles Gournay',
       'is_frequence': 'False',
       'direction_type': 'outbound',
       'codes': [{'type': 'Netex_ServiceJourneyPattern',
         'value': 'STBC:ServiceJourneyPattern:29796-C02129-37375:LOC'},
        {'type': 'Netex_ServiceJourneyPattern',
         'value': 'STBC:ServiceJourneyPattern:29796-C02129-37376:LOC'},
        {'type': 'source',
         'value': 'STBC:Route:29796-C02129-4044-RETOUR:LOC'}],
       'direction': {'id': 'stop_area:IDFM:68407',
        'name': 'Chelles - Gournay (Chelles)',
        'quality': 0,
        'stop_area': {'id': 'stop_area:IDFM:68407',
         'name': 'Chelles - Gournay',
         'codes': [{'type': 'TN_PA', 'value': '280'},
          {'type': 'source', 'value': 'FR::multimodalStopPlace:68407:FR1'}],
         'timezone': 'Europe/Paris',
         'label': 'Chelles - Gournay (Chelles)',
         'coord': {'lon': '2.583485', 'lat': '48.874745'},
         'links': []},
        'embedded_type': 'stop_area'},
       'geojson': {'type': 'MultiLineString', 'coordinates': []},
       'links': []}]}},
   {'pt_object': {'id': 'line:IDFM:C02129',
     'name': 'Apolo 7 Bus 3',
     'quality': 0,
     'line': {'id': 'line:IDFM:C02129',
      'name': '3',
      'code': '3',
      'color': 'B44A9C',
      'text_color': 'FFFFFF',
      'codes': [{'type': 'Netex_PrivateCode', 'value': '101361013'},
       {'type': 'source', 'value': 'FR1:Line:C02129:'}],
      'physical_modes': [{'id': 'physical_mode:Bus', 'name': 'Bus'}],
      'commercial_mode': {'id': 'commercial_mode:Bus', 'name': 'Bus'},
      'network': {'id': 'network:IDFM:6',
       'name': 'Apolo 7',
       'links': [],
       'codes': [{'type': 'source', 'value': 'FR1:Network:6:LOC'}]},
      'opening_time': '052000',
      'closing_time': '220800',
      'geojson': {'type': 'MultiLineString', 'coordinates': []},
      'links': []},
     'embedded_type': 'line'},
    'impacted_section': {'from': {'id': 'stop_area:IDFM:68680',
      'name': 'Collège Maria Callas (Courtry)',
      'quality': 0,
      'stop_area': {'id': 'stop_area:IDFM:68680',
       'name': 'Collège Maria Callas',
       'codes': [{'type': 'source',
         'value': 'FR::multimodalStopPlace:68680:FR1'}],
       'timezone': 'Europe/Paris',
       'label': 'Collège Maria Callas (Courtry)',
       'coord': {'lon': '2.603671', 'lat': '48.911249'},
       'links': []},
      'embedded_type': 'stop_area'},
     'to': {'id': 'stop_area:IDFM:68646',
      'name': 'Les Clos (Chelles)',
      'quality': 0,
      'stop_area': {'id': 'stop_area:IDFM:68646',
       'name': 'Les Clos',
       'codes': [{'type': 'source',
         'value': 'FR::multimodalStopPlace:68646:FR1'}],
       'timezone': 'Europe/Paris',
       'label': 'Les Clos (Chelles)',
       'coord': {'lon': '2.610341', 'lat': '48.903334'},
       'links': []},
      'embedded_type': 'stop_area'},
     'routes': [{'id': 'route:IDFM:STBC:29796-C02129-4044-ALLER',
       'name': 'Gare de Villeparisis Mitry-le-Neuf',
       'is_frequence': 'False',
       'direction_type': 'inbound',
       'codes': [{'type': 'Netex_ServiceJourneyPattern',
         'value': 'STBC:ServiceJourneyPattern:29796-C02129-37377:LOC'},
        {'type': 'Netex_ServiceJourneyPattern',
         'value': 'STBC:ServiceJourneyPattern:29796-C02129-37378:LOC'},
        {'type': 'source', 'value': 'STBC:Route:29796-C02129-4044-ALLER:LOC'}],
       'direction': {'id': 'stop_area:IDFM:68916',
        'name': 'Villeparisis - Mitry-le-Neuf (Mitry-Mory)',
        'quality': 0,
        'stop_area': {'id': 'stop_area:IDFM:68916',
         'name': 'Villeparisis - Mitry-le-Neuf',
         'codes': [{'type': 'TN_PA', 'value': '79'},
          {'type': 'source', 'value': 'FR::multimodalStopPlace:68916:FR1'}],
         'timezone': 'Europe/Paris',
         'label': 'Villeparisis - Mitry-le-Neuf (Mitry-Mory)',
         'coord': {'lon': '2.602796', 'lat': '48.953516'},
         'links': []},
        'embedded_type': 'stop_area'},
       'geojson': {'type': 'MultiLineString', 'coordinates': []},
       'links': []},
      {'id': 'route:IDFM:STBC:29796-C02129-4044-RETOUR',
       'name': 'Gare de Chelles Gournay',
       'is_frequence': 'False',
       'direction_type': 'outbound',
       'codes': [{'type': 'Netex_ServiceJourneyPattern',
         'value': 'STBC:ServiceJourneyPattern:29796-C02129-37375:LOC'},
        {'type': 'Netex_ServiceJourneyPattern',
         'value': 'STBC:ServiceJourneyPattern:29796-C02129-37376:LOC'},
        {'type': 'source',
         'value': 'STBC:Route:29796-C02129-4044-RETOUR:LOC'}],
       'direction': {'id': 'stop_area:IDFM:68407',
        'name': 'Chelles - Gournay (Chelles)',
        'quality': 0,
        'stop_area': {'id': 'stop_area:IDFM:68407',
         'name': 'Chelles - Gournay',
         'codes': [{'type': 'TN_PA', 'value': '280'},
          {'type': 'source', 'value': 'FR::multimodalStopPlace:68407:FR1'}],
         'timezone': 'Europe/Paris',
         'label': 'Chelles - Gournay (Chelles)',
         'coord': {'lon': '2.583485', 'lat': '48.874745'},
         'links': []},
        'embedded_type': 'stop_area'},
       'geojson': {'type': 'MultiLineString', 'coordinates': []},
       'links': []}]}}],
  'uri': '5f95054a-d707-11ef-b937-0a58a9feac02',
  'disruption_uri': 'b0e9ae60-d3f0-11ef-aa1a-0a58a9feac02',
  'contributor': 'shortterm.tr_idfm'},
 {'id': '4884f0e6-00cd-11f0-af9a-0a58a9feac02',
  'disruption_id': '48847fbc-00cd-11f0-af9a-0a58a9feac02',
  'impact_id': '4884f0e6-00cd-11f0-af9a-0a58a9feac02',
  'application_periods': [{'begin': '20250317T050000',
    'end': '20250607T235900'}],
  'status': 'active',
  'updated_at': '20250317T101640',
  'cause': 'perturbation',
  'category': 'Incidents',
  'severity': {'name': 'Bloquante passante',
   'effect': 'MODIFIED_SERVICE',
   'color': '#FF0000',
   'priority': 0},
  'messages': [{'text': '<p>En direction de Chelles : les arrêts Ampère et Rond-Point des Sciences ne seront pas desservis.<br>En direction de Montfermeil : l’arrêt Ampère ne sera pas desservi.<br>Du lundi 17 mars 2025 jusqu’à la fin des travaux jusqu’au samedi 07 juin 2025<br>En direction de Montfermeil : Veuillez-vous reporter à l’arrêt Rond-point des Sciences.<br>En direction de Chelles : Veuillez-vous reporter aux arrêts Arago (L5), ESAT (L5), Lavoisier (L5) et Claude Bernard<br>Nous vous prions de bien vouloir nous excuser pour la gêne occasionnée.</p>',
    'channel': {'content_type': 'text/html',
     'id': '3ae8df3e-7488-11e8-ac3b-005056a47b86',
     'name': 'moteur',
     'types': ['web']}},
   {'text': 'Transdev STBC Ligne 1',
    'channel': {'content_type': 'text/plain',
     'id': 'd9dbc5a6-7a06-11e8-8b8c-005056a44da2',
     'name': 'titre',
     'types': ['title']}}],
  'impacted_objects': [{'pt_object': {'id': 'line:IDFM:C01423',
     'name': 'Apolo 7 Bus 1',
     'quality': 0,
     'line': {'id': 'line:IDFM:C01423',
      'name': '1',
      'code': '1',
      'color': 'F9DC00',
      'text_color': '000000',
      'codes': [{'type': 'Netex_PrivateCode', 'value': '101261020'},
       {'type': 'source', 'value': 'FR1:Line:C01423:'}],
      'physical_modes': [{'id': 'physical_mode:Bus', 'name': 'Bus'}],
      'commercial_mode': {'id': 'commercial_mode:Bus', 'name': 'Bus'},
      'network': {'id': 'network:IDFM:6',
       'name': 'Apolo 7',
       'links': [],
       'codes': [{'type': 'source', 'value': 'FR1:Network:6:LOC'}]},
      'opening_time': '050000',
      'closing_time': '231900',
      'geojson': {'type': 'MultiLineString', 'coordinates': []},
      'links': []},
     'embedded_type': 'line'}},
   {'pt_object': {'id': 'stop_point:IDFM:16820',
     'name': 'Rond-Point des Sciences (Chelles)',
     'quality': 0,
     'stop_point': {'id': 'stop_point:IDFM:16820',
      'name': 'Rond-Point des Sciences',
      'codes': [{'type': 'netex_monomodal_stopplace',
        'value': 'monomodalStopPlace:56358'},
       {'type': 'netex_zder_quay', 'value': '15094'},
       {'type': 'netex_zder_quay', 'value': '16819'},
       {'type': 'netex_zder_quay', 'value': '16820'},
       {'type': 'netex_zder_quay', 'value': '19006'},
       {'type': 'netex_zder_quay', 'value': 'monomodalStopPlace:56358'},
       {'type': 'source', 'value': 'FR::Quay:16820:FR1'}],
      'label': 'Rond-Point des Sciences (Chelles)',
      'coord': {'lon': '2.588127', 'lat': '48.904056'},
      'links': [],
      'equipments': [],
      'address': {'id': '2.588127;48.904056',
       'name': 'Rond-Point des Sciences',
       'house_number': 0,
       'coord': {'lon': '2.588127', 'lat': '48.904056'},
       'label': 'Rond-Point des Sciences (Chelles)'},
      'fare_zone': {'name': '4'}},
     'embedded_type': 'stop_point'}},
   {'pt_object': {'id': 'stop_point:IDFM:16819',
     'name': 'Rond-Point des Sciences (Chelles)',
     'quality': 0,
     'stop_point': {'id': 'stop_point:IDFM:16819',
      'name': 'Rond-Point des Sciences',
      'codes': [{'type': 'netex_monomodal_stopplace',
        'value': 'monomodalStopPlace:56358'},
       {'type': 'netex_zder_quay', 'value': '15094'},
       {'type': 'netex_zder_quay', 'value': '16819'},
       {'type': 'netex_zder_quay', 'value': '16820'},
       {'type': 'netex_zder_quay', 'value': '19006'},
       {'type': 'netex_zder_quay', 'value': 'monomodalStopPlace:56358'},
       {'type': 'source', 'value': 'FR::Quay:16819:FR1'}],
      'label': 'Rond-Point des Sciences (Chelles)',
      'coord': {'lon': '2.588155', 'lat': '48.903948'},
      'links': [],
      'equipments': ['has_wheelchair_boarding'],
      'address': {'id': '2.588155;48.903948',
       'name': 'Rond-Point des Sciences',
       'house_number': 0,
       'coord': {'lon': '2.588155', 'lat': '48.903948'},
       'label': 'Rond-Point des Sciences (Chelles)'},
      'fare_zone': {'name': '4'}},
     'embedded_type': 'stop_point'}},
   {'pt_object': {'id': 'stop_point:IDFM:19398',
     'name': 'Ampère (Montfermeil)',
     'quality': 0,
     'stop_point': {'id': 'stop_point:IDFM:19398',
      'name': 'Ampère',
      'codes': [{'type': 'netex_monomodal_stopplace',
        'value': 'monomodalStopPlace:57306'},
       {'type': 'netex_zder_quay', 'value': '18978'},
       {'type': 'netex_zder_quay', 'value': '19398'},
       {'type': 'netex_zder_quay', 'value': 'monomodalStopPlace:57306'},
       {'type': 'source', 'value': 'FR::Quay:19398:FR1'}],
      'label': 'Ampère (Montfermeil)',
      'coord': {'lon': '2.585422', 'lat': '48.904595'},
      'links': [],
      'equipments': [],
      'address': {'id': '2.585422;48.904595',
       'name': 'Place Ampère',
       'house_number': 0,
       'coord': {'lon': '2.585422', 'lat': '48.904595'},
       'label': 'Place Ampère (Montfermeil)'},
      'fare_zone': {'name': '4'}},
     'embedded_type': 'stop_point'}}],
  'uri': '4884f0e6-00cd-11f0-af9a-0a58a9feac02',
  'disruption_uri': '48847fbc-00cd-11f0-af9a-0a58a9feac02',
  'contributor': 'shortterm.tr_idfm'},
 {'id': 'beac34e6-297d-11ef-9244-0a58a9feac02',
  'disruption_id': 'beaa3d44-297d-11ef-9244-0a58a9feac02',
  'impact_id': 'beac34e6-297d-11ef-9244-0a58a9feac02',
  'application_periods': [{'begin': '20240613T140902',
    'end': '20250613T140902'}],
  'status': 'active',
  'updated_at': '20240613T140911',
  'tags': ['Ascenseur'],
  'cause': 'perturbation',
  'category': 'Incidents',
  'severity': {'name': 'perturbée',
   'effect': 'SIGNIFICANT_DELAYS',
   'color': '#EF662F',
   'priority': 30},
  'messages': [{'text': "Panne d'un ascenseur",
    'channel': {'content_type': 'text/plain',
     'id': 'd9dbc5a6-7a06-11e8-8b8c-005056a44da2',
     'name': 'titre',
     'types': ['title']}},
   {'text': "SURESNES / LONGCHAMP Panne de l'ascenseur situé 4, rue Merlin de Thionville, direction La Défense - Issy - Val de Seine",
    'channel': {'content_type': 'text/html',
     'id': '3ae8df3e-7488-11e8-ac3b-005056a47b86',
     'name': 'moteur',
     'types': ['web']}},
   {'text': "SURESNES / LONGCHAMP Panne de l'ascenseur situé 4, rue Merlin de Thionville, direction La Défense - Issy - Val de Seine",
    'channel': {'content_type': 'text/html',
     'id': '0c0c032e-7a07-11e8-ab20-005056a47b86',
     'name': 'email ascenseur',
     'types': ['email']}},
   {'text': 'SURESNES / LONGCHAMP Panne ascenseur situé 4, rue Merlin de Thionville, dir. La Défense - Issy - Val de Seine',
    'channel': {'content_type': 'text/plain',
     'id': 'ea77b9e2-7a06-11e8-ab20-005056a47b86',
     'name': 'sms ascenseurs',
     'types': ['sms']}}],
  'impacted_objects': [{'pt_object': {'id': 'stop_area:IDFM:70811',
     'name': 'Suresnes Longchamp (Suresnes)',
     'quality': 0,
     'stop_area': {'id': 'stop_area:IDFM:70811',
      'name': 'Suresnes Longchamp',
      'codes': [{'type': 'source',
        'value': 'FR::multimodalStopPlace:70811:FR1'}],
      'timezone': 'Europe/Paris',
      'label': 'Suresnes Longchamp (Suresnes)',
      'coord': {'lon': '2.221624', 'lat': '48.867502'},
      'links': []},
     'embedded_type': 'stop_area'}}],
  'uri': 'beac34e6-297d-11ef-9244-0a58a9feac02',
  'disruption_uri': 'beaa3d44-297d-11ef-9244-0a58a9feac02',
  'contributor': 'shortterm.tr_idfm'},
 {'id': 'c8cfc682-5b90-11ef-b754-0a58a9feac02',
  'disruption_id': 'c8cd49c0-5b90-11ef-b754-0a58a9feac02',
  'impact_id': 'c8cfc682-5b90-11ef-b754-0a58a9feac02',
  'application_periods': [{'begin': '20240914T060000',
    'end': '20250831T235900'}],
  'status': 'active',
  'updated_at': '20240829T160022',
  'tags': ['Actualité'],
  'cause': 'information',
  'category': 'Communication',
  'severity': {'name': 'perturbée',
   'effect': 'SIGNIFICANT_DELAYS',
   'color': '#EF662F',
   'priority': 30},
  'messages': [{'text': '<p><span>⚠️🚍</span><span style="color:rgb(29,155,240);"><span>#InfoTrafic</span></span><span> - Lignes E, M et 12 -À partir du mercredi 04 Septembre 2024 : Tous les mercredis de 5h00 à 16h00</span><br>&nbsp;</p><p><span>Changement de Terminus Arrivée/ Départ :</span></p><p><span><strong>❌Arrêt Gare de Chatou parvis Nord non desservi</strong></span></p><p><span><strong>✅Report arrêt Gare de Chatou parvis Sud</strong></span></p><p><br>&nbsp;</p><p><span>Veuillez nous excuser de la gêne occasionnée.</span></p>',
    'channel': {'content_type': 'text/html',
     'id': '3ae8df3e-7488-11e8-ac3b-005056a47b86',
     'name': 'moteur',
     'types': ['web']}},
   {'text': '⚠️🚍#InfoTrafic - Lignes E, M, 12 - à partir du 4/09/24 tous les mercredis et samedis',
    'channel': {'content_type': 'text/plain',
     'id': '17eac900-7a07-11e8-a990-005056a47b86',
     'name': 'notification',
     'types': ['notification']}},
   {'text': '⚠️🚍#InfoTrafic - Lignes E, M et 12 -À partir du mercredi 04 Septembre 2024 : Tous les mercredis de 5h00 à 16h00',
    'channel': {'content_type': 'text/plain',
     'id': 'd9dbc5a6-7a06-11e8-8b8c-005056a44da2',
     'name': 'titre',
     'types': ['title']}}],
  'impacted_objects': [{'pt_object': {'id': 'line:IDFM:C00336',
     'name': 'Argenteuil - Boucles de Seine Bus M',
     'quality': 0,
     'line': {'id': 'line:IDFM:C00336',
      'name': 'M',
      'code': 'M',
      'color': '8CE39C',
      'text_color': 'FFFFFF',
      'codes': [{'type': 'Netex_PrivateCode', 'value': '000533021'},
       {'type': 'source', 'value': 'FR1:Line:C00336:'}],

In [40]:
import requests
import pandas as pd

# URL de base de l'API
base_url = "https://prim.iledefrance-mobilites.fr/marketplace/v2/navitia/line_reports/line_reports"
headers = {
    "apikey": API_KEY  # Remplace avec ta vraie clé API
}

# Pagination
start_page = 0
items_per_page = 25
all_rows = []

while True:
    params = {
        "start_page": start_page,
        "count": items_per_page
    }
    
    response = requests.get(base_url, headers=headers, params=params)
    
    if response.status_code != 200:
        print(f"Erreur {response.status_code} à la page {start_page}")
        break

    json_data = response.json()
    disruptions = json_data.get("disruptions", [])

    if not disruptions:
        break  # Plus de disruptions à parcourir

    # Traitement de chaque disruption
    for disruption in disruptions:
        html_message = next(
            (msg['text'] for msg in disruption.get('messages', [])
             if msg.get('channel', {}).get('content_type') == 'text/html'),
            None
        )
        
        row = {
            'priority': disruption['severity']['priority'],
            'effect': disruption['severity']['effect'],
            'severity_text': disruption['severity']['name'],
            #'begin': disruption['application_periods'][0]['begin'],
            #'end': disruption['application_periods'][0]['end'],
            'id': disruption['id'],
            'text': html_message
        }
        all_rows.append(row)

    print(f"Page {start_page} traitée avec {len(disruptions)} disruptions.")
    
    # Vérification fin de pagination
    pagination = json_data.get('pagination', {})
    total_result = pagination.get('total_result', 0)
    if (start_page + 1) * items_per_page >= total_result:
        break

    start_page += 1

# Construction du DataFrame
df_v2 = pd.DataFrame(all_rows)

Page 0 traitée avec 15 disruptions.
Page 1 traitée avec 26 disruptions.
Page 2 traitée avec 18 disruptions.
Page 3 traitée avec 22 disruptions.
Page 4 traitée avec 9 disruptions.
Page 5 traitée avec 31 disruptions.
Page 6 traitée avec 16 disruptions.
Page 7 traitée avec 25 disruptions.
Page 8 traitée avec 92 disruptions.
Page 9 traitée avec 22 disruptions.
Page 10 traitée avec 21 disruptions.
Page 11 traitée avec 7 disruptions.
Page 12 traitée avec 13 disruptions.
Page 13 traitée avec 17 disruptions.
Page 14 traitée avec 24 disruptions.
Page 15 traitée avec 57 disruptions.
Page 16 traitée avec 51 disruptions.
Page 17 traitée avec 70 disruptions.
Page 18 traitée avec 62 disruptions.
Page 19 traitée avec 60 disruptions.
Page 20 traitée avec 54 disruptions.
Page 21 traitée avec 70 disruptions.
Page 22 traitée avec 58 disruptions.
Page 23 traitée avec 47 disruptions.
Page 24 traitée avec 68 disruptions.
Page 25 traitée avec 141 disruptions.
Page 26 traitée avec 199 disruptions.
Page 27 traitée avec 22 disruptions.
Page 28 traitée avec 35 disruptions.
Page 29 traitée avec 51 disruptions.
Page 30 traitée avec 210 disruptions.
Page 31 traitée avec 52 disruptions.
Page 32 traitée avec 32 disruptions.
Page 33 traitée avec 24 disruptions.
Page 34 traitée avec 6 disruptions.

In [41]:
df_v2.head(3)

,priority,effect,severity_text,id,text
0,0,MODIFIED_SERVICE,Bloquante passante,5f95054a-d707-11ef-b937-0a58a9feac02,"<p>En raison de travaux, avenue de Chantereine..."
1,0,MODIFIED_SERVICE,Bloquante passante,4884f0e6-00cd-11f0-af9a-0a58a9feac02,<p>En direction de Chelles : les arrêts Ampère...
2,30,SIGNIFICANT_DELAYS,perturbée,beac34e6-297d-11ef-9244-0a58a9feac02,SURESNES / LONGCHAMP Panne de l'ascenseur situ...

provisoire en dessous

In [42]:
"""# Conversion des dates
df_current_filtered.loc[:, 'begin'] = pd.to_datetime(df_current_filtered['begin'], format="%Y%m%dT%H%M%S", errors='coerce')
df_current_filtered.loc[:, 'end'] = pd.to_datetime(df_current_filtered['end'], format="%Y%m%dT%H%M%S", errors='coerce')

# Conversion des dates
df_v2['begin'] = pd.to_datetime(df_v2['begin'], format="%Y%m%dT%H%M%S", errors='coerce')
df_v2['end'] = pd.to_datetime(df_v2['end'], format="%Y%m%dT%H%M%S", errors='coerce')"""

'# Conversion des dates\ndf_current_filtered.loc[:, \'begin\'] = pd.to_datetime(df_current_filtered[\'begin\'], format="%Y%m%dT%H%M%S", errors=\'coerce\')\ndf_current_filtered.loc[:, \'end\'] = pd.to_datetime(df_current_filtered[\'end\'], format="%Y%m%dT%H%M%S", errors=\'coerce\')\n\n# Conversion des dates\ndf_v2[\'begin\'] = pd.to_datetime(df_v2[\'begin\'], format="%Y%m%dT%H%M%S", errors=\'coerce\')\ndf_v2[\'end\'] = pd.to_datetime(df_v2[\'end\'], format="%Y%m%dT%H%M%S", errors=\'coerce\')'

In [43]:
df_current_v2_merged = pd.merge(df_current_filtered, df_v2, on=['id'], how='left')
#df_current_v2_merged = pd.merge(df_current_filtered, df_v2, on=['id', 'begin', 'end'], how='left')

In [44]:
df_current_v2_merged.shape

(11, 18)

In [45]:
df_current_v2_merged.head(3)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode,status,priority,effect,severity_text,text
0,2025-03-27 18:42:00,2025-04-22 04:30:00,26847bb8-0b33-11f0-b7af-0a58a9feac02,20250327T184436,TRAVAUX,BLOQUANTE,[Actualité],Tramway T1 : Travaux - Trafic interrompu,"Jusqu'au lundi 21 avril 2025, le trafic est in...",Trafic interrompu,"[Auguste Delaune, Bobigny - Pablo Picasso, Esc...",T1,Tramway,now,0.0,NO_SERVICE,bloquante,"<p>Jusqu'au lundi 21 avril 2025, le trafic est..."
1,2025-04-08 08:15:00,2025-04-08 16:20:00,99c8f304-f2c1-11ef-96bd-0a58a9feac02,20250224T161119,TRAVAUX,PERTURBEE,[Actualité],Ligne E : Nanterre- Chelles 7 - 11/04,Période : de 8h15 à 16h15Dates : du lundi 7 au...,trafic ralenti,"[Bondy, Chelles - Gournay, Gagny, Haussmann Sa...",E,RapidTransit,now,30.0,SIGNIFICANT_DELAYS,perturbée,<p>P&#233;riode : de 8h15 &#224; 16h15<br><br>...
2,2025-04-08 09:00:00,2025-04-08 16:00:00,97f26936-0ed5-11f0-ac05-0a58a9feac02,20250401T104458,TRAVAUX,PERTURBEE,[Actualité],Ligne D Goussainville Melun 03 mars au 22 août...,Période : de 09h00 à 16h00.Dates : du lundi 3 ...,trafic ralenti,"[Boussy-Saint-Antoine, Brunoy, Châtelet les Ha...",D,RapidTransit,now,30.0,SIGNIFICANT_DELAYS,perturbée,<p>P&#233;riode : de 09h00 &#224; 16h00.<br><b...

In [46]:
df_current_v2_merged['text'][0]

"<p>Jusqu'au lundi 21 avril 2025, le trafic est interrompu entre Gare de Noisy-le-Sec et Escadrille Normandie-Niémen en raison de travaux. .<br>Bus de remplacement.<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"

# recuperer le nombre de validations de voyageurs

In [65]:
n_validation = pd.read_csv("../data/nb_vald_par_arret_jour.csv", sep=";", encoding="utf-8")
n_validation.iloc[177:183].head(10)
# Filtrer les données pour une date spécifique
aujourd_hui = datetime.now()
#aujourd_hui = datetime(2023, 10, 1)  # Exemple de date spécifique
yearFormat = aujourd_hui.strftime('%Y-%m-%d') 
lastYearToday = (aujourd_hui.replace(year=aujourd_hui.year - 1)).strftime('%Y-%m-%d')
# Afficher les résultats
print(f"la date aujourd_hui {aujourd_hui} :")
print(f"la date yearFormat {yearFormat} :")
print(f"la date lastYear {lastYearToday} :")

la date aujourd_hui 2025-04-08 16:22:38.875086 :
la date yearFormat 2025-04-08 :
la date lastYear 2024-04-08 :

In [66]:
# Convertir les noms des arrêts en minuscules
n_validation['libelle_arret'] = n_validation['libelle_arret'].str.lower()
numb = 0
stations_valid_day = []
# Filtrer les données pour la date spécifique
filtered_validation = n_validation[n_validation['jour'] == lastYearToday]

# Vérifier les arrêts dans df_current_v2_merged
for stop_points in df_current_v2_merged['stop_points']:
    for stop in stop_points:
        if stop.lower() in filtered_validation['libelle_arret'].values:
            # Récupérer le nombre de validations correspondant
            nb_vald = filtered_validation.loc[filtered_validation['libelle_arret'] == stop.lower(), 'nb_vald'].values
            if len(nb_vald) > 0:
                stations_valid_day.append(f"{stop} {nb_vald[0]}")
                numb += 1

print(numb)
print(stations_valid_day)

21
['Magenta 6075', 'Pantin 8862', 'Rosa Parks 14798', 'Brunoy 5782', 'Gare de Lyon 115382', 'Gare du Nord 105502', 'Goussainville 5443', 'Yerres 4483', 'Brunoy 5782', 'Gare de Lyon 115382', 'Gare du Nord 105502', 'Goussainville 5443', 'Yerres 4483', 'Bougival 686', 'Courbevoie 2967', 'Louveciennes 694', 'Pont Cardinet 7', 'Puteaux 2787', 'Vaucresson 1538', 'Chartrettes 24', 'Montereau 3058']

In [ ]:
from datetime import datetime

# Convertir les colonnes 'begin' et 'end' en datetime si ce n'est pas déjà fait
df_current_v2_merged['begin'] = pd.to_datetime(df_current_v2_merged['begin'], format='%Y%m%dT%H%M%S', errors='coerce')
df_current_v2_merged['end'] = pd.to_datetime(df_current_v2_merged['end'], format='%Y%m%dT%H%M%S', errors='coerce')

# Ajouter une colonne 'total_valid_imp' initialisée à 0
df_current_v2_merged['total_valid_imp'] = 0

# Filtrer les données pour la date spécifique
filtered_validation = n_validation[n_validation['jour'] == lastYearToday]

# Parcourir chaque ligne de df_current_v2_merged
for index, row in df_current_v2_merged.iterrows():
    stop_points = row['stop_points']  # Liste des arrêts impactés
    begin = row['begin']
    end = row['end']
    
    # Vérifier que begin et end sont valides
    if pd.notnull(begin) and pd.notnull(end):
        # Calculer la durée en heures entre begin et end
        duration_hours = (end - begin).total_seconds() / 3600
        
        # Filtrer les validations pour les arrêts impactés
        total_validations = 0
        for stop in stop_points:
            stop_lower = stop.lower()  # Convertir en minuscules pour correspondance
            if stop_lower in filtered_validation['libelle_arret'].str.lower().values:
                # Récupérer le nombre de validations correspondant
                nb_vald = filtered_validation.loc[filtered_validation['libelle_arret'].str.lower() == stop_lower, 'nb_vald'].values
                if len(nb_vald) > 0:
                    total_validations += nb_vald[0]
        
        # Réduire le total des validations en fonction de la durée
        # Supposons que les validations sont réparties uniformément sur 24 heures
        impacted_validations = total_validations * (duration_hours / 24)
        
        # Ajouter le résultat dans la colonne 'total_valid_imp'
        df_current_v2_merged.at[index, 'total_valid_imp'] = round(impacted_validations)

# Afficher un aperçu du DataFrame mis à jour
print(df_current_v2_merged[['id' ,'stop_points', 'begin', 'end', 'total_valid_imp']].head())

                                     id  \
0  26847bb8-0b33-11f0-b7af-0a58a9feac02
1  99c8f304-f2c1-11ef-96bd-0a58a9feac02
2  97f26936-0ed5-11f0-ac05-0a58a9feac02
3  6bd130e6-10c7-11f0-8f48-0a58a9feac02
4  cb00c832-1479-11f0-88c2-0a58a9feac02

                                         stop_points               begin  \
0  [Auguste Delaune, Bobigny - Pablo Picasso, Esc... 2025-03-27 18:42:00
1  [Bondy, Chelles - Gournay, Gagny, Haussmann Sa... 2025-04-08 08:15:00
2  [Boussy-Saint-Antoine, Brunoy, Châtelet les Ha... 2025-04-08 09:00:00
3  [Boussy-Saint-Antoine, Brunoy, Châtelet les Ha... 2025-04-08 09:00:00
4  [Asnières-sur-Seine, Bougival, Bécon les Bruyè... 2025-04-08 14:42:14

                  end  total_valid_imp
0 2025-04-22 04:30:00                0
1 2025-04-08 16:20:00            10015
2 2025-04-08 16:00:00            69006
3 2025-04-08 16:00:00            69006
4 2025-04-08 16:00:00              469

In [68]:
df_current_v2_merged.head(3)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode,status,priority,effect,severity_text,text,total_valid_imp
0,2025-03-27 18:42:00,2025-04-22 04:30:00,26847bb8-0b33-11f0-b7af-0a58a9feac02,20250327T184436,TRAVAUX,BLOQUANTE,[Actualité],Tramway T1 : Travaux - Trafic interrompu,"Jusqu'au lundi 21 avril 2025, le trafic est in...",Trafic interrompu,"[Auguste Delaune, Bobigny - Pablo Picasso, Esc...",T1,Tramway,now,0.0,NO_SERVICE,bloquante,"<p>Jusqu'au lundi 21 avril 2025, le trafic est...",0
1,2025-04-08 08:15:00,2025-04-08 16:20:00,99c8f304-f2c1-11ef-96bd-0a58a9feac02,20250224T161119,TRAVAUX,PERTURBEE,[Actualité],Ligne E : Nanterre- Chelles 7 - 11/04,Période : de 8h15 à 16h15Dates : du lundi 7 au...,trafic ralenti,"[Bondy, Chelles - Gournay, Gagny, Haussmann Sa...",E,RapidTransit,now,30.0,SIGNIFICANT_DELAYS,perturbée,<p>P&#233;riode : de 8h15 &#224; 16h15<br><br>...,10015
2,2025-04-08 09:00:00,2025-04-08 16:00:00,97f26936-0ed5-11f0-ac05-0a58a9feac02,20250401T104458,TRAVAUX,PERTURBEE,[Actualité],Ligne D Goussainville Melun 03 mars au 22 août...,Période : de 09h00 à 16h00.Dates : du lundi 3 ...,trafic ralenti,"[Boussy-Saint-Antoine, Brunoy, Châtelet les Ha...",D,RapidTransit,now,30.0,SIGNIFICANT_DELAYS,perturbée,<p>P&#233;riode : de 09h00 &#224; 16h00.<br><b...,69006

In [69]:
df_current_v2_merged.to_csv('df_current_final.csv', index = False)
df_preview_filtered.to_csv('df_preview_final.csv', index = False)

In [70]:
df_current_final = pd.read_csv('df_current_final.csv')
df_current_final.head(3)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode,status,priority,effect,severity_text,text,total_valid_imp
0,2025-03-27 18:42:00,2025-04-22 04:30:00,26847bb8-0b33-11f0-b7af-0a58a9feac02,20250327T184436,TRAVAUX,BLOQUANTE,['Actualité'],Tramway T1 : Travaux - Trafic interrompu,"Jusqu'au lundi 21 avril 2025, le trafic est in...",Trafic interrompu,"['Auguste Delaune', 'Bobigny - Pablo Picasso',...",T1,Tramway,now,0.0,NO_SERVICE,bloquante,"<p>Jusqu'au lundi 21 avril 2025, le trafic est...",0
1,2025-04-08 08:15:00,2025-04-08 16:20:00,99c8f304-f2c1-11ef-96bd-0a58a9feac02,20250224T161119,TRAVAUX,PERTURBEE,['Actualité'],Ligne E : Nanterre- Chelles 7 - 11/04,Période : de 8h15 à 16h15Dates : du lundi 7 au...,trafic ralenti,"['Bondy', 'Chelles - Gournay', 'Gagny', 'Hauss...",E,RapidTransit,now,30.0,SIGNIFICANT_DELAYS,perturbée,<p>P&#233;riode : de 8h15 &#224; 16h15<br><br>...,10015
2,2025-04-08 09:00:00,2025-04-08 16:00:00,97f26936-0ed5-11f0-ac05-0a58a9feac02,20250401T104458,TRAVAUX,PERTURBEE,['Actualité'],Ligne D Goussainville Melun 03 mars au 22 août...,Période : de 09h00 à 16h00.Dates : du lundi 3 ...,trafic ralenti,"['Boussy-Saint-Antoine', 'Brunoy', 'Châtelet l...",D,RapidTransit,now,30.0,SIGNIFICANT_DELAYS,perturbée,<p>P&#233;riode : de 09h00 &#224; 16h00.<br><b...,69006

In [71]:
df_preview_final = pd.read_csv('df_preview_final.csv')
df_preview_final.head(3)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode
0,2025-04-08 22:00:00,2025-04-09 04:30:00,e0812420-ad56-11ef-b233-0a58a9feac02,20241128T080331,TRAVAUX,BLOQUANTE,['Actualité'],Métro 14 : Travaux - Trafic interrompu,"Du 3 mars au 15 avril, les lundi et mardi à pa...",NaN,"['Bercy', 'Bibliothèque François Mitterrand', ...",14,Metro
1,2025-04-08 22:45:00,2025-04-09 02:45:00,e5f599c4-0632-11f0-9201-0a58a9feac02,20250321T100012,TRAVAUX,BLOQUANTE,['Actualité'],Ligne B : Châtelet - CDG2/Mitry du 31/03 au 25/04,"Période : du lundi au vendredi, à partir de 22...",Trafic interrompu planifié,"['Antony', 'Arcueil - Cachan', 'Aulnay-sous-Bo...",B,RapidTransit
2,2025-04-08 22:00:00,2025-04-09 04:30:00,4e42f940-0f34-11f0-8f48-0a58a9feac02,20250401T220258,TRAVAUX,BLOQUANTE,['Actualité'],Métro 14 : Travaux - Trafic interrompu,"Jusqu'au 29 avril, les lundi et mardi à partir...",Trafic interrompu,"['Bercy', 'Bibliothèque François Mitterrand', ...",14,Metro

In [61]:
#print(df_preview_final.isnull().sum())

In [62]:
#print(df_current_final.isnull().sum())

In [76]:
import pandas as pd
import ast
from bs4 import BeautifulSoup

def clean_and_describe_csv(file_path, title):
    # Lire le fichier CSV
    df = pd.read_csv(file_path)
    df = df.fillna(" ")  # Remplacer les NaN par une chaîne vide
    # Nettoyer les colonnes
    df['tags'] = df['tags'].apply(ast.literal_eval)
    df['stop_points'] = df['stop_points'].apply(ast.literal_eval)

    # Nettoyer la colonne 'text' si elle existe
    if 'text' in df.columns:
        df['text'] = df['text'].apply(lambda x: BeautifulSoup(x, "html.parser").get_text())
    """if 'total_valid_imp' in df.columns:
        if df['total_valid_imp'].values[0] == 0:
            df['total_valid_imp'].replace(0, 'valeur inconnu')"""

    descriptions = [title]
    for index, row in df.iterrows():
        description = (
            f"De {row['begin']} à {row['end']}, l'événement avec l'ID {row['id']} "
            f"(dernière mise à jour le {row['lastUpdate']}) est causé par {row['cause']}. "
            f"La sévérité est {row.get('severity_text', 'non spécifiée')}. "
            f"Les balises associées sont {', '.join(row['tags'])}. "
            f"Le titre de l'événement est : {row['title']}. "
            f"Message : {row['message']}. "
            f"Message court : {row['shortMessage']}. "
            f"Points d'arrêt affectés : {', '.join(row['stop_points'])}. "
            f"Nom : {row['name']}. Mode : {row['mode']}. "
        )
        if 'status' in row:
            description += f"Statut : {row['status']}. "
        if 'priority' in row:
            description += f"Priorité : {row['priority']}. "
        if 'effect' in row:
            description += f"Effet : {row['effect']}. "
        if 'text' in row:
            description += f"Texte : {row['text']}. "
        if 'total_valid_imp' in row:
            description += f"Voyageurs impactés : {'valeur inconnu' if row['total_valid_imp'] == 0 else row['total_valid_imp']}."        
        descriptions.append(description)
    return descriptions

# Traiter chaque CSV séparément avec des titres distinctifs
file_paths = ['df_current_final.csv', 'df_preview_final.csv']
titles = ["Perturbations en cours :", "Perturbations à venir :"]
descriptions_list = [clean_and_describe_csv(file_path, title) for file_path, title in zip(file_paths, titles)]

# Réunir les descriptions des deux CSV dans une seule variable
combined_descriptions = "\n\n".join(["\n".join(descriptions) for descriptions in descriptions_list])

# Afficher les descriptions combinées
print("Descriptions combinées des deux CSV :\n")
print(combined_descriptions)

Descriptions combinées des deux CSV :

Perturbations en cours :
De 2025-03-27 18:42:00 à 2025-04-22 04:30:00, l'événement avec l'ID 26847bb8-0b33-11f0-b7af-0a58a9feac02 (dernière mise à jour le 20250327T184436) est causé par TRAVAUX. La sévérité est bloquante. Les balises associées sont Actualité. Le titre de l'événement est : Tramway T1 : Travaux - Trafic interrompu. Message : Jusqu'au lundi 21 avril 2025, le trafic est interrompu entre Gare de Noisy-le-Sec et Escadrille Normandie-Niémen en raison de travaux. .Bus de remplacement.Plus d'informations sur le site ratp.fr. Message court : Trafic interrompu. Points d'arrêt affectés : Auguste Delaune, Bobigny - Pablo Picasso, Escadrille Normandie-Niemen, Gare de Noisy-le-Sec, Hôtel de Ville de Bobigny, Jean Rostand, La Ferme, Libération, Petit Noisy, Pont de Bondy. Nom : T1. Mode : Tramway. Statut : now. Priorité : 0.0. Effet : NO_SERVICE. Texte : Jusqu'au lundi 21 avril 2025, le trafic est interrompu entre Gare de Noisy-le-Sec et Escadrille Normandie-Niémen en raison de travaux. .Bus de remplacement.Plus d'informations sur le site ratp.fr. Voyageurs impactés : valeur inconnu.
De 2025-04-08 08:15:00 à 2025-04-08 16:20:00, l'événement avec l'ID 99c8f304-f2c1-11ef-96bd-0a58a9feac02 (dernière mise à jour le 20250224T161119) est causé par TRAVAUX. La sévérité est perturbée. Les balises associées sont Actualité. Le titre de l'événement est : Ligne E : Nanterre- Chelles 7 - 11/04. Message : Période : de 8h15 à 16h15Dates : du lundi 7 au vendredi 11 avril Un train sur deux circule en moyenne. Les horaires des trains de Nanterre-la-Folie vers Chelles Gournay sont modifiés de 8h15 à 16h15 le lundi et de 8h15 à 16h00 du mardi au vendredi. Le train NOMY, au départ Magenta - Gare du Nord à 16h22 pour Nanterre-la-Folie, est retiré de la circulation : le prochain train est le train NOCY au passage à Magenta - Gare du Nord à 16h30.Lundi, les trains CONY de 10h49 et 14h19 et NOCY de 15h33 circulent. Ils sont retirés de la circulation du mardi au vendredi. Lundi, les trains CONY de 14h49 et NOCY de 16h03 sont retirés de la circulation. Ils circulent du mardi au vendredi. Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux.. Message court : trafic ralenti. Points d'arrêt affectés : Bondy, Chelles - Gournay, Gagny, Haussmann Saint-Lazare, La Défense, Le Chénay Gagny, Le Raincy - Villemomble - Montfermeil, Magenta, Nanterre-La-Folie, Neuilly Porte Maillot, Noisy-le-Sec, Pantin, Rosa Parks. Nom : E. Mode : RapidTransit. Statut : now. Priorité : 30.0. Effet : SIGNIFICANT_DELAYS. Texte : Période : de 8h15 à 16h15Dates : du lundi 7 au vendredi 11 avril Un train sur deux circule en moyenne. Les horaires des trains de Nanterre-la-Folie vers Chelles Gournay sont modifiés de 8h15 à 16h15 le lundi et de 8h15 à 16h00 du mardi au vendredi. Le train NOMY, au départ Magenta - Gare du Nord à 16h22 pour Nanterre-la-Folie, est retiré de la circulation : le prochain train est le train NOCY au passage à Magenta - Gare du Nord à 16h30.Lundi, les trains CONY de 10h49 et 14h19 et NOCY de 15h33 circulent. Ils sont retirés de la circulation du mardi au vendredi. Lundi, les trains CONY de 14h49 et NOCY de 16h03 sont retirés de la circulation. Ils circulent du mardi au vendredi. Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux.. Voyageurs impactés : 10015.
De 2025-04-08 09:00:00 à 2025-04-08 16:00:00, l'événement avec l'ID 97f26936-0ed5-11f0-ac05-0a58a9feac02 (dernière mise à jour le 20250401T104458) est causé par TRAVAUX. La sévérité est perturbée. Les balises associées sont Actualité. Le titre de l'événement est : Ligne D Goussainville Melun 03 mars au 22 août 2025. Message : Période : de 09h00 à 16h00.Dates : du lundi 3 mars au vendredi 22 aout, hors week-end et jours fériés.Un train sur deux circule au départ ou est limité à Combs La Ville. Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux sur les voies de garage à Melun.. Message court : trafic ralenti. Points d'arrêt affectés : Boussy-Saint-Antoine, Brunoy, Châtelet les Halles, Combs-la-Ville - Quincy, Créteil Pompadour, Gare de Lyon, Gare du Nord, Garges - Sarcelles, Goussainville, Le Vert de Maisons, Maisons-Alfort - Alfortville, Montgeron - Crosne, Pierrefitte - Stains, Saint-Denis, Stade de France Saint-Denis, Villeneuve Triage, Villeneuve-Saint-Georges, Villiers-le-Bel - Gonesse - Arnouville, Yerres. Nom : D. Mode : RapidTransit. Statut : now. Priorité : 30.0. Effet : SIGNIFICANT_DELAYS. Texte : Période : de 09h00 à 16h00.Dates : du lundi 3 mars au vendredi 22 aout, hors week-end et jours fériés.Un train sur deux circule au départ ou est limité à Combs La Ville. Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux sur les voies de garage à Melun.. Voyageurs impactés : 69006.
De 2025-04-08 09:00:00 à 2025-04-08 16:00:00, l'événement avec l'ID 6bd130e6-10c7-11f0-8f48-0a58a9feac02 (dernière mise à jour le 20250403T220834) est causé par TRAVAUX. La sévérité est perturbée. Les balises associées sont Actualité. Le titre de l'événement est : RER D Goussainville Melun 06 mars au 22 août 2025. Message : Période : du lundi au vendredi sauf jours fériés, de 09h00 à 16h00.Dates : du 03/02/2025 au 22/08/2025Un train sur deux circule au départ ou est limité à Combs La Ville. Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux sur les voies de garage à Melun.. Message court : trafic ralenti. Points d'arrêt affectés : Boussy-Saint-Antoine, Brunoy, Châtelet les Halles, Combs-la-Ville - Quincy, Créteil Pompadour, Gare de Lyon, Gare du Nord, Garges - Sarcelles, Goussainville, Le Vert de Maisons, Maisons-Alfort - Alfortville, Montgeron - Crosne, Pierrefitte - Stains, Saint-Denis, Stade de France Saint-Denis, Villeneuve Triage, Villeneuve-Saint-Georges, Villiers-le-Bel - Gonesse - Arnouville, Yerres. Nom : D. Mode : RapidTransit. Statut : now. Priorité : 30.0. Effet : SIGNIFICANT_DELAYS. Texte : Période : du lundi au vendredi sauf jours fériés, de 09h00 à 16h00.Dates : du 03/02/2025 au 22/08/2025Un train sur deux circule au départ ou est limité à Combs La Ville. Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux sur les voies de garage à Melun.. Voyageurs impactés : 69006.
De 2025-04-08 14:42:14 à 2025-04-08 16:00:00, l'événement avec l'ID cb00c832-1479-11f0-88c2-0a58a9feac02 (dernière mise à jour le 20250408T150257) est causé par PERTURBATION. La sévérité est perturbée. Les balises associées sont Actualité. Le titre de l'événement est : Ligne L : Paris <-> St-Nom-la-Bret. trafic fortement perturbé. Message : Le trafic est fortement perturbé entre Paris Saint-Lazare et St-Nom-la-Bretèche dans les 2 sens. Pour plus d'informations sur cette perturbation, consultez le fil Twitter de la ligne L. Motif : panne d'un passage à niveau dans le secteur de Garches-Marne-la-Coquette.. Message court : trafic ralenti. Points d'arrêt affectés : Asnières-sur-Seine, Bougival, Bécon les Bruyères, Clichy - Levallois, Courbevoie, Garches - Marnes-la-Coquette, Gare Saint-Lazare, L'Étang-la-Ville, La Celle-Saint-Cloud, La Défense, Le Val d'Or, Louveciennes, Marly-le-Roi, Pont Cardinet, Puteaux, Saint-Cloud, Saint-Nom-la-Bretèche Forêt de Marly, Suresnes Mont Valérien, Vaucresson. Nom : L. Mode : LocalTrain. Statut : new. Priorité : 30.0. Effet : SIGNIFICANT_DELAYS. Texte : Le trafic est fortement perturbé entre Paris Saint-Lazare et St-Nom-la-Bretèche dans les 2 sens. Pour plus d'informations sur cette perturbation, consultez le fil Twitter de la ligne L. Motif : panne d'un passage à niveau dans le secteur de Garches-Marne-la-Coquette.. Voyageurs impactés : 469.
De 2025-04-08 15:34:42 à 2025-04-08 18:35:00, l'événement avec l'ID 29616a08-147f-11f0-8f48-0a58a9feac02 (dernière mise à jour le 20250408T154126) est causé par PERTURBATION. La sévérité est perturbée. Les balises associées sont Actualité. Le titre de l'événement est : ligne R : Melun - Montereau via Héricy : suppression. Message : Train supprimé :-  KOHO, départ de Melun à 17h57, arrivée à Montereau à 18h34.Risque d'affluence à bord du train suivant.Prochain train à circuler :-  KOHO, départ de Melun à 18h19, arrivée à Montereau à 18h56.Pour plus d'informations sur cette perturbation, consultez le fil Twitter de la ligne.Motif : conditions de départ non réunies.. Message court : trafic ralenti. Points d'arrêt affectés : Champagne-sur-Seine, Chartrettes, Fontaine-le-Port, Héricy, La Grande-Paroisse, Livry-sur-Seine, Melun, Montereau, Vernou-sur-Seine, Vulaines-sur-Seine - Samoreau. Nom : R. Mode : LocalTrain. Statut : new. Priorité : 30.0. Effet : SIGNIFICANT_DELAYS. Texte : Train supprimé :-  KOHO, départ de Melun à 17h57, arrivée à Montereau à 18h34.Risque d'affluence à bord du train suivant.Prochain train à circuler :-  KOHO, départ de Melun à 18h19, arrivée à Montereau à 18h56.Pour plus d'informations sur cette perturbation, consultez le fil Twitter de la ligne.Motif : conditions de départ non réunies.. Voyageurs impactés : 386.
De   à  , l'événement avec l'ID 4716a674-1049-11f0-8f48-0a58a9feac02 (dernière mise à jour le 20250403T070536) est causé par TRAVAUX. La sévérité est bloquante. Les balises associées sont Actualité. Le titre de l'événement est : Ligne D : Corbeil - Malesherbes du 07/04 au 11/04. Message : Période : de 10h11 à  14h18Dates : du lundi 7 avril au vendredi 11 avril 2025.Le trafic est interrompu entre Corbeil-Essonnes et Malesherbes.Un service de bus de remplacement est mis en place, avec desserte des gares intermédiaires.Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux de maintenance.. Message court : Trafic interrompu planifié. Points d'arrêt affectés : Ballancourt, Boigneville, Boutigny, Buno - Gironville, Corbeil-Essonnes, Gare de Lyon, Grand Bourg, Juvisy, La Ferté-Alais, Le Vert de Maisons, Maisons-Alfort - Alfortville, Maisse, Malesherbes, Mennecy, Moulin Galant, Ris-Orangis, Vigneux-sur-Seine, Villeneuve-Saint-Georges, Viry-Châtillon, Évry - Val de Seine. Nom : D. Mode : RapidTransit. Statut : finished. Priorité : 0.0. Effet : NO_SERVICE. Texte : Période : de 10h11 à  14h18Dates : du lundi 7 avril au vendredi 11 avril 2025.Le trafic est interrompu entre Corbeil-Essonnes et Malesherbes.Un service de bus de remplacement est mis en place, avec desserte des gares intermédiaires.Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux de maintenance.. Voyageurs impactés : valeur inconnu.
De   à  , l'événement avec l'ID e1ce714c-11b1-11f0-b7af-0a58a9feac02 (dernière mise à jour le 20250405T020655) est causé par TRAVAUX. La sévérité est bloquante. Les balises associées sont Actualité. Le titre de l'événement est : RER C : 3 gares non desservies du 31/03 au 11/04.. Message : Période : De 09h15 à 15h30.Dates : Du lundi 31 mars au vendredi 11 avril.Les gares des Ardoines, Vitry sur Seine et Ivry sur Seine ne sont plus desservies par les trains en direction de Paris.Report : Lignes du Métro, Tramway et lignes de bus de ville Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux de maintenance.. Message court : Arrêt non desservi planifié. Points d'arrêt affectés : Ablon, Arpajon, Athis-Mons, Avenue Foch, Avenue Henri Martin, Avenue du Président Kennedy Maison de Radio France, Bibliothèque François Mitterrand, Boulainvilliers, Bouray, Breuillet - Bruyères-le-Châtel, Breuillet Village, Brétigny, Cernay, Champ de Mars Tour Eiffel, Chaville - Vélizy, Chemin d'Antony, Choisy-le-Roi, Dourdan, Dourdan la Forêt, Ermont - Eaubonne, Franconville - Le Plessis-Bouchard, Gare d'Austerlitz, Gare de Chamarande, Gennevilliers, Invalides, Issy, Issy - Val de Seine, Ivry-sur-Seine, Javel, Juvisy, La Norville - Saint-Germain-lès-Arpajon, Lardy, Les Ardoines, Les Grésillons, Les Saules, Marolles-en-Hurepoix, Massy - Palaiseau, Massy - Verrières, Meudon Val Fleury, Montigny - Beauchamp, Musée d'Orsay, Neuilly Porte Maillot, Orly Ville, Pierrelaye, Pont de Rungis Aéroport d'Orly, Pont de l'Alma, Pont du Garigliano - Hôpital Européen G. Pompidou, Pontoise, Porchefontaine, Porte de Clichy, Péreire Levallois, Rungis la Fraternelle, Saint-Chéron, Saint-Cyr, Saint-Gratien, Saint-Martin d'Étampes, Saint-Michel Notre-Dame, Saint-Michel-sur-Orge, Saint-Ouen, Saint-Ouen-l'Aumône, Saint-Ouen-l'Aumône Liesse, Saint-Quentin en Yvelines - Montigny-le-Bretonneux, Sainte-Geneviève-des-Bois, Savigny-sur-Orge, Sermaise, Versailles Chantiers, Versailles Château Rive Gauche, Villeneuve-le-Roi, Viroflay Rive Gauche, Vitry-sur-Seine, Égly, Épinay-sur-Orge, Épinay-sur-Seine, Étampes, Étréchy. Nom : C. Mode : RapidTransit. Statut : finished. Priorité : 0.0. Effet : NO_SERVICE. Texte : Période : De 09h15 à 15h30.Dates : Du lundi 31 mars au vendredi 11 avril.Les gares des Ardoines, Vitry sur Seine et Ivry sur Seine ne sont plus desservies par les trains en direction de Paris.Report : Lignes du Métro, Tramway et lignes de bus de ville Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux de maintenance.. Voyageurs impactés : valeur inconnu.
De   à  , l'événement avec l'ID fdeebd8a-1474-11f0-88c2-0a58a9feac02 (dernière mise à jour le 20250408T142836) est causé par PERTURBATION. La sévérité est  . Les balises associées sont Actualité. Le titre de l'événement est : Métro 5 : Bagage oublié sur un quai - Trafic interrompu. Message : Le trafic est interrompu entre République et Place d'Italie en raison d'un bagage oublié sur un quai à Bastille . Heure de reprise estimée : 15:30.Nous vous invitons à emprunter des itinéraires alternatifs et à vous rapprocher de nos agents.Plus d'informations sur le site ratp.fr. Message court : Trafic interrompu. Points d'arrêt affectés : Bastille, Bréguet-Sabin, Campo-Formio, Gare d'Austerlitz, Oberkampf, Place d'Italie, Quai de la Rapée, Richard-Lenoir, République, Saint-Marcel. Nom : 5. Mode : Metro. Statut : finished. Priorité :  . Effet :  . Texte :  . Voyageurs impactés : valeur inconnu.
De   à  , l'événement avec l'ID 8d6cd580-ed12-11ef-b7e6-0a58a9feac02 (dernière mise à jour le 20250217T103540) est causé par TRAVAUX. La sévérité est perturbée. Les balises associées sont Actualité. Le titre de l'événement est : Ligne E : Nanterre - Villiers 7 - 11/04. Message : Période : de 10h00 à 15h00Dates : du lundi 7 au vendredi 11 avrilLes horaires des trains de Nanterre-la-Folie vers Villiers-sur-Marne - Le Plessis-Trévise sont avancés ou retardés.Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux.. Message court : trafic ralenti. Points d'arrêt affectés : Haussmann Saint-Lazare, La Défense, Les Boullereaux Champigny, Magenta, Nanterre-La-Folie, Neuilly Porte Maillot, Nogent - Le Perreux, Noisy-le-Sec, Pantin, Rosa Parks, Rosny Bois Perrier, Rosny-sous-Bois, Val de Fontenay, Villiers-sur-Marne - Le Plessis-Trévise. Nom : E. Mode : RapidTransit. Statut : finished. Priorité : 30.0. Effet : SIGNIFICANT_DELAYS. Texte : Période : de 10h00 à 15h00Dates : du lundi 7 au vendredi 11 avrilLes horaires des trains de Nanterre-la-Folie vers Villiers-sur-Marne - Le Plessis-Trévise sont avancés ou retardés.Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux.. Voyageurs impactés : valeur inconnu.
De   à  , l'événement avec l'ID eb9cbaae-10c5-11f0-8f48-0a58a9feac02 (dernière mise à jour le 20250403T215749) est causé par TRAVAUX. La sévérité est perturbée. Les balises associées sont Actualité. Le titre de l'événement est : Montereau<>Melun via Héricy: travaux du 31/03 au 18/04. Message : Période : de 10h26 à 15h30.Date : Du lundi 31 mars au vendredi 18 avril 2025 (hors week-end).Le trafic est interrompu de 10h26 à 15h30 entre Melun et Montereau via Héricy. Un service de bus de remplacement est mis en place pour assurer vos déplacements. A noter:Les horaires de certains trains peuvent être avancés. Nous vous conseillons de consulter la rubrique "recherche itinéraire" pour préparer vos trajets.Motif : travaux de maintenance. . Message court : trafic ralenti. Points d'arrêt affectés : Bois-le-Roi, Champagne-sur-Seine, Chartrettes, Fontaine-le-Port, Fontainebleau - Avon, Héricy, La Grande-Paroisse, Livry-sur-Seine, Melun, Montereau, Moret - Veneux-les-Sablons, Saint-Mammès, Thomery, Vernou-sur-Seine, Vulaines-sur-Seine - Samoreau. Nom : R. Mode : LocalTrain. Statut : finished. Priorité : 30.0. Effet : SIGNIFICANT_DELAYS. Texte : Période : de 10h26 à 15h30.Date : Du lundi 31 mars au vendredi 18 avril 2025 (hors week-end).Le trafic est interrompu de 10h26 à 15h30 entre Melun et Montereau via Héricy. Un service de bus de remplacement est mis en place pour assurer vos déplacements. A noter:Les horaires de certains trains peuvent être avancés. Nous vous conseillons de consulter la rubrique "recherche itinéraire" pour préparer vos trajets.Motif : travaux de maintenance. . Voyageurs impactés : valeur inconnu.

Perturbations à venir :
De 2025-04-08 22:00:00 à 2025-04-09 04:30:00, l'événement avec l'ID e0812420-ad56-11ef-b233-0a58a9feac02 (dernière mise à jour le 20241128T080331) est causé par TRAVAUX. La sévérité est non spécifiée. Les balises associées sont Actualité. Le titre de l'événement est : Métro 14 : Travaux - Trafic interrompu. Message : Du 3 mars au 15 avril, les lundi et mardi à partir de 22:00, le trafic sera interrompu entre Maison Blanche et Saint-Denis - Pleyel en raison de travaux. Bus entre Gare de Lyon et OlympiadesPlus d'informations sur le site ratp.fr. Message court :  . Points d'arrêt affectés : Bercy, Bibliothèque François Mitterrand, Châtelet, Cour Saint-Emilion, Gare de Lyon, Madeleine, Mairie de Saint-Ouen, Maison Blanche, Olympiades, Pont Cardinet, Porte de Clichy, Pyramides, Saint-Denis - Pleyel, Saint-Lazare, Saint-Ouen. Nom : 14. Mode : Metro.
De 2025-04-08 22:45:00 à 2025-04-09 02:45:00, l'événement avec l'ID e5f599c4-0632-11f0-9201-0a58a9feac02 (dernière mise à jour le 20250321T100012) est causé par TRAVAUX. La sévérité est non spécifiée. Les balises associées sont Actualité. Le titre de l'événement est : Ligne B : Châtelet - CDG2/Mitry du 31/03 au 25/04. Message : Période : du lundi au vendredi, à partir de 22h45Dates : du 31 mars au 25 avril 2025, sauf les 18 et 21 avril 2025Le trafic est interrompu entre Châtelet-les-Halles et Aéroport CDG2-TGV / Mitry-Claye. Un service de bus de remplacement est mis en place, avec desserte des gares intermédiaires. Pour plus d'informations, consultez le site du RER B. Les horaires du calculateur d'itinéraire tiennent compte des travaux.Motif : travaux. Message court : Trafic interrompu planifié. Points d'arrêt affectés : Antony, Arcueil - Cachan, Aulnay-sous-Bois, Aéroport CDG 1 (Terminal 3) - RER, Aéroport Charles de Gaulle 2 (Terminal 2), Bagneux, Bourg-la-Reine, Bures-sur-Yvette, Châtelet les Halles, Cité Universitaire, Courcelle-sur-Yvette, Denfert-Rochereau, Drancy, Fontaine Michalon, Fontenay-aux-Roses, Gare du Nord, Gentilly, Gif-sur-Yvette, La Courneuve - Aubervilliers, La Croix de Berny, La Hacquinière, La Plaine Stade de France, Laplace, Le Blanc-Mesnil, Le Bourget, Le Guichet, Les Baconnets, Lozère, Luxembourg, Massy - Palaiseau, Massy - Verrières, Mitry - Claye, Orsay Ville, Palaiseau, Palaiseau - Villebon, Parc de Sceaux, Parc des Expositions, Port Royal, Robinson, Saint-Michel Notre-Dame, Saint-Rémy-lès-Chevreuse, Sceaux, Sevran - Livry, Sevran Beaudottes, Vert Galant, Villeparisis - Mitry-le-Neuf, Villepinte. Nom : B. Mode : RapidTransit.

Comment lire les indications temporelles

begin 20241012T020900

2024 : Année

10 : Mois (octobre)

12 : Jour

T : Séparateur entre la date et l'heure (utilisé pour indiquer que ce qui suit est l'heure)

02 : Heure (2 heures du matin)

09 : Minute

00 : Seconde