In [353]:
import pandas as pd
import requests
import json

# **API REQUETE GLOBALE** #

In [354]:
# CALL API
API_KEY = "haj00y9FzSQ1VZCTUjpmla8Q98xRnA6a"

URL = 'https://prim.iledefrance-mobilites.fr/marketplace/disruptions_bulk/disruptions/v2'

headers = {
    "Accept": "application/json",
    "apikey": API_KEY
}

response = requests.get(URL, headers=headers)

if response.status_code == 200:
    data = response.json()
    print(data)
else:
    print(f"Erreur {response.status_code}: {response.text}")

{'disruptions': [{'id': '74316236-8627-11ef-aca5-0a58a9feac02', 'applicationPeriods': [{'begin': '20241012T020900', 'end': '20241013T233400'}, {'begin': '20241019T120900', 'end': '20241020T230900'}, {'begin': '20241207T020900', 'end': '20241208T234400'}, {'begin': '20250118T020900', 'end': '20250119T234900'}, {'begin': '20250329T020900', 'end': '20250330T235400'}, {'begin': '20250405T030400', 'end': '20250406T234900'}, {'begin': '20250412T030400', 'end': '20250413T234900'}], 'lastUpdate': '20250401T120646', 'cause': 'TRAVAUX', 'severity': 'BLOQUANTE', 'tags': ['Actualité'], 'title': 'Travaux boulevard Carnot et Calmette', 'message': '<p>En raison de travaux boulevard Carnot et Calmette à Mantes-la-Jolie, les arrêts suivants ne seront pas desservis :</p><p>Ligne D : (Plaisances) Carnot reporté à Louise Michel et Calmette reporté à Mantes-la-Ville Mairie</p><p>Ligne N : Calmette et Carnot reportés à Mantes-Station</p><p>Ligne A14 : Calmette reporté à Mantes-Station</p><p>les samedis 05 et 12 avril 2025, et les dimanches 6 et 13 avril 2025</p><p>Nous vous prions de nous excuser de la gêne occasionnée.</p>'}, {'id': '36842782-ad4d-11ef-b233-0a58a9feac02', 'applicationPeriods': [{'begin': '20250514T220000', 'end': '20250515T043000'}, {'begin': '20250521T220000', 'end': '20250522T043000'}], 'lastUpdate': '20241128T065421', 'cause': 'TRAVAUX', 'severity': 'BLOQUANTE', 'tags': ['Actualité'], 'title': 'Métro 14 : Travaux - Trafic interrompu', 'message': "<p>Du 14 mai au 21 mai, le mercredi à partir de 22:00, le trafic sera interrompu sur l'ensemble de la ligne en raison de travaux. <br>Bus de remplacement entre Gare de Lyon et Olympiades<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"}, {'id': '3cb5d628-ad4d-11ef-a448-0a58a9feac02', 'applicationPeriods': [{'begin': '20250604T220000', 'end': '20250605T043000'}, {'begin': '20250611T220000', 'end': '20250612T043000'}, {'begin': '20250618T220000', 'end': '20250619T043000'}, {'begin': '20250625T220000', 'end': '20250626T043000'}, {'begin': '20250702T220000', 'end': '20250703T043000'}, {'begin': '20250709T220000', 'end': '20250710T043000'}, {'begin': '20250716T220000', 'end': '20250717T043000'}, {'begin': '20250723T220000', 'end': '20250724T043000'}], 'lastUpdate': '20241128T065431', 'cause': 'TRAVAUX', 'severity': 'BLOQUANTE', 'tags': ['Actualité'], 'title': 'Métro 14 : Travaux - Trafic interrompu', 'message': "<p>Du 4 juin au 23 juillet, le mercredi à partir de 22:00, le trafic sera interrompu sur l'ensemble de la ligne en raison de travaux. <br>Bus de remplacement entre Gare de Lyon et Olympiades<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"}, {'id': 'e0812420-ad56-11ef-b233-0a58a9feac02', 'applicationPeriods': [{'begin': '20250303T220000', 'end': '20250304T043000'}, {'begin': '20250304T220000', 'end': '20250305T043000'}, {'begin': '20250310T220000', 'end': '20250311T043000'}, {'begin': '20250311T220000', 'end': '20250312T043000'}, {'begin': '20250317T220000', 'end': '20250318T043000'}, {'begin': '20250318T220000', 'end': '20250319T043000'}, {'begin': '20250324T220000', 'end': '20250325T043000'}, {'begin': '20250325T220000', 'end': '20250326T043000'}, {'begin': '20250331T220000', 'end': '20250401T043000'}, {'begin': '20250401T220000', 'end': '20250402T043000'}, {'begin': '20250407T220000', 'end': '20250408T043000'}, {'begin': '20250408T220000', 'end': '20250409T043000'}, {'begin': '20250414T220000', 'end': '20250415T043000'}, {'begin': '20250415T220000', 'end': '20250416T043000'}], 'lastUpdate': '20241128T080331', 'cause': 'TRAVAUX', 'severity': 'BLOQUANTE', 'tags': ['Actualité'], 'title': 'Métro 14 : Travaux - Trafic interrompu', 'message': "<p>Du 3 mars au 15 avril, les lundi et mardi à partir de 22:00, le trafic sera interrompu entre Maison Blanche et Saint-Denis - Pleyel en raison de travaux. <br>Bus entre Gare de Lyon et Olympiades<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"}, {'id': '4cd7123e-b1bb-11ef-845d-0a58a9feac02', 'applicationPeriods': [{'begin': '20250412T044500', 'end': '20250414T043000'}], 'lastUpdate': '20241203T221227', 'cause': 'TRAVAUX', 'severity': 'BLOQUANTE', 'tags': ['Actualité'], 'title': 'Métro 6 : Travaux de modernisation - Trafic interrompu', 'message': "<p>Du 12 avril au 13 avril, le trafic sera interrompu entre Nation et Daumesnil en raison de travaux de modernisation.<br>Bus de remplacement.<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"}, {'id': '5939bd2e-b1bb-11ef-ab9b-0a58a9feac02', 'applicationPeriods': [{'begin': '20250525T044500', 'end': '20250526T043000'}], 'lastUpdate': '20241203T221248', 'cause': 'TRAVAUX', 'severity': 'BLOQUANTE', 'tags': ['Actualité'], 'title': 'Métro 6 : Travaux de modernisation - Trafic interrompu', 'message': "<p>Le 25 mai, le trafic sera interrompu entre Charles de Gaulle - Etoile et Trocadéro en direction de Nation en raison de travaux de modernisation.<br>Bus de remplacement.<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"}, {'id': '5d2decf2-b1bb-11ef-845d-0a58a9feac02', 'applicationPeriods': [{'begin': '20250518T044500', 'end': '20250519T043000'}], 'lastUpdate': '20241203T221256', 'cause': 'TRAVAUX', 'severity': 'BLOQUANTE', 'tags': ['Actualité'], 'title': 'Métro 6 : Travaux de modernisation - Trafic interrompu', 'message': "<p>Le 18 mai, le trafic sera interrompu entre Daumesnil et Nation en raison de travaux de modernisation.<br>Bus de remplacement.<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"}, {'id': '6190e7ea-b1bb-11ef-ab9b-0a58a9feac02', 'applicationPeriods': [{'begin': '20250615T044500', 'end': '20250616T043000'}], 'lastUpdate': '20241203T221302', 'cause': 'TRAVAUX', 'severity': 'BLOQUANTE', 'tags': ['Actualité'], 'title': 'Métro 6 : Travaux de modernisation - Trafic interrompu', 'message': "<p>Le 15 juin, le trafic sera interrompu sur l'ensemble de la ligne en raison de travaux de modernisation.<br><a href='http://www.ratp.fr'>Plus d'informations sur le site ratp.fr</a></p>"}, {'id': '4a2946e2-beae-11ef-b1c7-0a58a9feac02', 'applicationPeriods': [{'begin': '20250106T010000', 'end': '20250606T230000'}], 'lastUpdate': '20241220T094303', 'cause': 'TRAVAUX', 'severity': 'BLOQUANTE', 'title': '4414, 4438 et TàD Etréchy, Travaux Chauffour-lès-Etréchy', 'message': "<p>Lignes 4414, 4438 et TàD Etréchy, du 6/01/2025 au 6/06/2025, en raison de travaux à Chauffour-lès-Etréchy l'arrêt “Grande Rue” sera reporté à la sortie du village en direction de Villeconin dans les 2 sens</p>"}, {'id': '4e10e836-cea4-11ef-bc79-0a58a9feac02', 'applicationPeriods': [{'begin': '20250113T000000', 'end': '20250113T235900'}, {'begin': '20250114T000000', 'end': '20250114T235900'}, {'begin': '20250115T000000', 'end': '20250115T235900'}, {'begin': '20250116T000000', 'end': '20250116T235900'}, {'begin': '20250117T000000', 'end': '20250117T235900'}, {'begin': '20250120T000000', 'end': '20250120T235900'}, {'begin': '20250121T000000', 'end': '20250121T235900'}, {'begin': '20250122T000000', 'end': '20250122T235900'}, {'begin': '20250123T000000', 'end': '20250123T235900'}, {'begin': '20250124T000000', 'end': '20250124T235900'}, {'begin': '20250127T000000', 'end': '20250127T235900'}, {'begin': '20250128T000000', 'end': '20250128T235900'}, {'begin': '20250129T000000', 'end': '20250129T235900'}, {'begin': '20250130T000000', 'end': '20250130T235900'}, {'begin': '20250131T000000', 'end': '20250131T235900'}, {'begin': '20250203T000000', 'end': '20250203T235900'}, {'begin': '20250204T000000', 'end': '20250204T235900'}, {'begin': '20250205T000000', 'end': '20250205T235900'}, {'begin': '20250206T000000', 'end': '20250206T235900'}, {'begin': '20250207T000000', 'end': '20250207T235900'}, {'begin': '20250210T000000', 'end': '20250210T235900'}, {'begin': '20250211T000000', 'end': '20250211T235900'}, {'begin': '20250212T000000', 'end': '20250212T235900'}, {'begin': '20250213T000000', 'end': '20250213T235900'}, {'begin': '20250214T000000', 'end': '20250214T235900'}, {'begin': '20250217T000000', 'end': '20250217T235900'}, {'begin': '20250218T000000', 'end': '20250218T235900'}, {'begin': '20250219T000000', 'end': '20250219T235900'}, {'begin': '20250220T000000', 'end': '20250220T235900'}, {'begin': '20250221T000000', 'end': '20250221T235900'}, {'begin': '20250224T000000', 'end': '20250224T235900'}, {'begin': '20250225T000000', 'end': '20250225T235900'}, {'begin': '20250226T000000', 'end': '20250226T235900'}, {'begin': '20250227T000000', 'end': '20250227T235900'}, {'begin': '20250228T000000', 'end': '20250228T235900'}, {'begin': '20250303T000000', 'end': '20250303T235900'}, {'begin': '20250304T000000', 'end': '20250304T235900'}, {'begin': '20250305T000000', 'end': '20250305T235900'}, {'begin': '20250306T000000', 'end': '20250306T235900'}, {'begin': '20250307T000000', 'end': '20250307T235900'}, {'begin': '20250310T000000', 'end': '20250310T235900'}, {'begin': '20250311T000000', 'end': '20250311T235900'}, {'begin': '20250312T000000', 'end': '20250312T235900'}, {'begin': '20250313T000000', 'end': '20250313T235900'}, {'begin': '20250314T000000', 'end': '20250314T235900'}, {'begin': '20250317T000000', 'end': '20250317T235900'}, {'begin': '20250318T000000', 'end': '20250318T235900'}, {'begin': '20250319T000000', 'end': '20250319T235900'}, {'begin': '20250320T000000', 'end': '20250320T235900'}, {'begin': '20250321T000000', 'end': '20250321T235900'}, {'begin': '20250324T000000', 'end': '20250324T235900'}, {'begin': '20250325T000000', 'end': '20250325T235900'}, {'begin': '20250326T000000', 'end': '20250326T235900'}, {'begin': '20250327T000000', 'end': '20250327T235900'}, {'begin': '20250328T000000', 'end': '20250328T235900'}, {'begin': '20250331T000000', 'end': '20250331T235900'}, {'begin': '20250401T000000', 'end': '20250401T235900'}, {'begin': '20250402T000000', 'end': '20250402T235900'}, {'begin': '20250403T000000', 'end': '20250403T235900'}, {'begin': '20250404T000000', 'end': '20250404T235900'}, {'begin': '20250407T000000', 'end': '20250407T235900'}, {'begin': '20250408T000000', 'end': '20250408T235900'}, {'begin': '20250409T000000', 'end': '20250409T235900'}, {'begin': '20250410T000000', 'end': '20250410T235900'}, {'begin': '20250411T000000', 'end': '20250411T235900'}, {'begin': '20250414T000000', 'end': '20250414T235900'}, {'begin': '20250415T000000', 'end': '20250415T235900'}, {'begin': '20250416T000000', 'end': '20250416T235900'}, {'begin': '20250417T000000', 'end': '20250417T235900'}, {'begin': '20250418T000000', 'end': '20250418T235900'}, {'begin': '20250421T000000', 'end': '20250421T235900'}, {'begin': '20250422T000000', 'end': '20250422T235900'}, {'begin': '20250423T000000', 'end': '20250423T235900'}, {'begin': '20250424T000000', 'end': '20250424T235900'}, {'begin': '20250425T000000', 'end': '20250425T235900'}, {'begin': '20250428T000000', 'end': '20250428T235900'}, {'begin': '20250429T000000', 'end': '20250429T235900'}, {'begin': '20250430T000000', 'end': '20250430T235900'}, {'begin': '20250501T000000', 'end': '20250501T235900'}, {'begin': '20250502T000000', 'end': '20250502T235900'}, {'begin': '20250505T000000', 'end': '20250505T235900'}, {'begin': '20250506T000000', 'end': '20250506T235900'}, {'begin': '20250507T000000', 'end': '20250507T235900'}, {'begin': '20250508T000000', 'end': '20250508T235900'}, {'begin': '20250509T000000', 'end': '20250509T235900'}, {'begin': '20250512T000000', 'end': '20250512T235900'}, {'begin': '20250513T000000', 'end': '20250513T235900'}, {'begin': '20250514T000000', 'end': '20250514T235900'}, {'begin': '20250515T000000', 'end': '20250515T235900'}, {'begin': '20250516T000000', 'end': '20250516T235900'}, {'begin': '20250519T000000', 'end': '20250519T235900'}, {'begin': '20250520T000000', 'end': '20250520T235900'}, {'begin': '20250521T000000', 'end': '20250521T235900'}, {'begin': '20250522T000000', 'end': '20250522T235900'}, {'begin': '20250523T000000', 'end': '20250523T235900'}, {'begin': '20250526T000000', 'end': '20250526T235900'}, {'begin': '20250527T000000', 'end': '20250527T235900'}, {'begin': '20250528T000000', 'end': '20250528T235900'}, {'begin': '20250529T000000', 'end': '20250529T235900'}, {'begin': '20250530T000000', 'end': '20250530T235900'}, {'begin': '20250602T000000', 'end': '20250602T235900'}, {'begin': '20250603T000000', 'end': '20250603T235900'}, {'begin': '20250604T000000', 'end': '20250604T235900'}, {'begin': '20250605T000000', 'end': '20250605T235900'}, {'begin': '20250606T000000', 'end': '20250606T235900'}, {'begin': '20250609T000000', 'end': '20250609T235900'}, {'begin': '20250610T000000', 'end': '20250610T235900'}, {'begin': '20250611T000000', 'end': '20250611T235900'}, {'begin': '20250612T000000', 'end': '20250612T235900'}, {'begin': '20250613T000000', 'end': '20250613T235900'}, {'begin': '20250616T000000', 'end': '20250616T235900'}, {'begin': '20250617T000000', 'end': '20250617T235900'}, {'begin': '20250618T000000', 'end': '20250618T235900'}, {'begin': '20250619T000000', 'end': '20250619T235900'}, {'begin': '20250620T000000', 'end': '20250620T235900'}, {'begin': '20250623T000000', 'end': '20250623T235900'}, {'begin': '20250624T000000', 'end': '20250624T235900'}, {'begin': '20250625T000000', 'end': '20250625T235900'}, {'begin': '20250626T000000', 'end': '20250626T235900'}, {'begin': '20250627T000000', 'end': '20250627T235900'}, {'begin': '20250630T000000', 'end': '20250630T235900'}, {'begin': '20250701T000000', 'end': '20250701T235900'}, {'begin': '20250702T000000', 'end': '20250702T235900'}, {'begin': '20250703T000000', 'end': '20250703T235900'}, {'begin': '20250704T000000', 'end': '20250704T235900'}, {'begin': '20250707T000000', 'end': '20250707T235900'}, {'begin': '20250708T000000', 'end': '20250708T235900'}, {'begin': '20250709T000000', 'end': '20250709T235900'}, {'begin': '20250710T000000', 'end': '20250710T235900'}, {'begin': '20250711T000000', 'end': '20250711T235900'}, {'begin': '20250714T000000', 'end': '20250714T235900'}, {'begin': '20250715T000000', 'end': '20250715T235900'}, {'begin': '20250716T000000', 'end': '20250716T235900'}, {'begin': '20250717T000000', 'end': '20250717T235900'}, {'begin': '20250718T000000', 'end': '20250718T235900'}, {'begin': '20250721T000000', 'end': '20250721T235900'}, {'begin': '20250722T000000', 'end': '20250722T235900'}, {'begin': '20250723T000000', 'end': '20250723T235900'}, {'begin': '20250724T000000', 'end': '20250724T235900'}, {'begin': '20250725T000000', 'end': '20250725T235900'}, {'begin': '20250728T000000', 'end': '20250728T235900'}, {'begin': '20250729T000000', 'end': '20250729T235900'}, {'begin': '20250730T000000', 'end': '20250730T235900'}, {'begin': '20250731T000000', 'end': '20250731T235900'}, {'begin': '20250801T000000', 'end': '20250801T235900'}, {'begin': '20250804T000000', 'end': '20250804T235900'}, {'begin': '20250805T000000', 'end': '20250805T235900'}, {'begin': '20250806T000000', 'end': '20250806T235900'}, {'begin': '20250807T000000', 'end': '20250807T235900'}, {'begin': '20250808T000000', 'end': '20250808T235900'}, {'begin': '20250811T000000', 'end': '20250811T235900'}, {'begin': '20250812T000000', 'end': '20250812T235900'}, {'begin': '20250813T000000', 'end': '20250813T235900'}, {'begin': '20250814T000000', 'end': '20250814T235900'}, {'begin': '20250815T000000', 'end': '20250815T235900'}, {'begin': '20250818T000000', 'end': '20250818T235900'}, {'begin': '20250819T000000', 'end': '20250819T235900'}, {'begin': '20250820T000000', 'end': '20250820T235900'}, {'begin': '20250821T000000', 'end': '20250821T235900'}, {'begin': '20250822T000000', 'end': '20250822T235900'}, {'begin': '20250825T000000', 'end': '20250825T235900'}, {'begin': '20250826T000000', 'end': '20250826T235900'}, {'begin': '20250827T000000', 'end': '20250827T235900'}, {'begin': '20250828T000000', 'end': '20250828T235900'}, {'begin': '20250829T000000', 'end': '20250829T235900'}, {'begin': '20250901T000000', 'end': '20250901T235900'}, {'begin': '20250902T000000', 'end': '20250902T235900'}, {'begin': '20250903T000000', 'end': '20250903T235900'}, {'begin': '20250904T000000', 'end': '20250904T235900'}, {'begin': '20250905T000000', 'end': '20250905T235900'}, {'begin': '20250908T000000', 'end': '20250908T235900'}, {'begin': '20250909T000000', 'end': '20250909T235900'}, {'begin': '20250910T000000', 'end': '20250910T235900'}, {'begin': '20250911T000000', 'end': '20250911T235900'}, {'begin': '20250912T000000', 'end': '20250912T235900'}, {'begin': '20250915T000000', 'end': '20250915T235900'}, {'begin': '20250916T000000', 'end': '20250916T235900'}, {'begin': '20250917T000000', 'end': '20250917T235900'}, {'begin': '20250918T000000', 'end': '20250918T235900'}, {'begin': '20250919T000000', 'end': '20250919T235900'}, {'begin': '20250922T000000', 'end': '20250922T235900'}, {'begin': '20250923T000000', 'end': '20250923T235900'}, {'begin': '20250924T000000', 'end': '20250924T235900'}, {'begin': '20250925T000000', 'end': '20250925T235900'}, {'begin': '20250926T000000', 'end': '20250926T235900'}, {'begin': '20250929T000000', 'end': '20250929T235900'}, {'begin': '20250930T000000', 'end': '20250930T235900'}, {'begin': '20251001T000000', 'end': '20251001T235900'}, {'begin': '20251002T000000', 'end': '20251002T235900'}, {'begin': '20251003T000000', 'end': '20251003T235900'}, {'begin': '20251006T000000', 'end': '20251006T235900'}, {'begin': '20251007T000000', 'end': '20251007T235900'}, {'begin': '20251008T000000', 'end': '20251008T235900'}, {'begin': '20251009T000000', 'end': '20251009T235900'}, {'begin': '20251010T000000', 'end': '20251010T235900'}, {'begin': '20251013T000000', 'end': '20251013T235900'}, {'begin': '20251014T000000', 'end': '20251014T235900'}, {'begin': '20251015T000000', 'end': '20251015T235900'}, {'begin': '20251016T000000', 'end': '20251016T235900'}, {'begin': '20251017T000000', 'end': '20251017T235900'}, {'begin': '20251020T000000', 'end': '20251020T235900'}, {'begin': '20251021T000000', 'end': '20251021T235900'}, {'begin': '20251022T000000', 'end': '20251022T235900'}, {'begin': '20251023T000000', 'end': '20251023T235900'}, {'begin': '20251024T000000', 'end': '20251024T235900'}, {'begin': '20251027T000000', 'end': '20251027T235900'}, {'begin': '20251028T000000', 'end': '20251028T235900'}, {'begin': '20251029T000000', 'end': '20251029T235900'}, {'begin': '20251030T000000', 'end': '20251030T235900'}, {'begin': '20251031T000000', 'end': '20251031T235900'}, {'begin': '20251103T000000', 'end': '20251103T235900'}, {'begin': '20251104T000000', 'end': '20251104T235900'}, {'begin': '20251105T000000', 'end': '20251105T235900'}, {'begin': '20251106T000000', 'end': '20251106T235900'}, {'begin': '20251107T000000', 'end': '20251107T235900'}, {'begin': '20251110T000000', 'end': '20251110T235900'}, {'begin': '20251111T000000', 'end': '20251111T235900'}, {'begin': '20251112T000000', 'end': '20251112T235900'}, {'begin': '20251113T000000', 'end': '20251113T235900'}, {'begin': '20251114T000000', 'end': '20251114T235900'}, {'begin': '20251117T000000', 'end': '20251117T235900'}, {'begin': '20251118T000000', 'end': '20251118T235900'}, {'begin': '20251119T000000', 'end': '20251119T235900'}, {'begin': '20251120T000000', 'end': '20251120T235900'}, {'begin': '20251121T000000', 'end': '20251121T235900'}, {'begin': '20251124T000000', 'end': '20251124T235900'}, {'begin': '20251125T000000', 'end': '20251125T235900'}, {'begin': '20251126T000000', 'end': '20251126T235900'}, {'begin': '20251127T000000', 'end': '20251127T235900'}, {'begin': '20251128T000000', 'end': '20251128T235900'}, {'begin': '20251201T000000', 'end': '20251201T235900'}, {'begin': '20251202T000000', 'end': '20251202T235900'}, {'begin': '20251203T000000', 'end': '20251203T235900'}, {'begin': '20251204T000000', 'end': '20251204T235900'}, {'begin': '20251205T000000', 'end': '20251205T235900'}, {'begin': '20251208T000000', 'end': '20251208T235900'}, {'begin': '20251209T000000', 'end': '20251209T235900'}, {'begin': '20251210T000000', 'end': '20251210T23

## **Récupérer les données présente dna sles clés API** ##

In [355]:
# Accéder aux clés des perturbations
disruptions = data.get("disruptions", [])

In [356]:
# Accéder aux clés des arrêts concernés
lines = data.get("lines", [])

In [357]:
lines

[{'id': 'line:IDFM:C01423',
  'name': '1',
  'shortName': '1',
  'mode': 'Bus',
  'networkId': 'network:IDFM:6',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01423',
    'name': '1',
    'disruptionIds': ['4884f0e6-00cd-11f0-af9a-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16820',
    'name': 'Rond-Point des Sciences',
    'disruptionIds': ['4884f0e6-00cd-11f0-af9a-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16819',
    'name': 'Rond-Point des Sciences',
    'disruptionIds': ['4884f0e6-00cd-11f0-af9a-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:19398',
    'name': 'Ampère',
    'disruptionIds': ['4884f0e6-00cd-11f0-af9a-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02129',
  'name': '3',
  'shortName': '3',
  'mode': 'Bus',
  'networkId': 'network:IDFM:6',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02129',
    'name': '3',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02',
     'd47a59a6-d28d-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16703',
    'name': 'Les Clos',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:479809',
    'name': 'Le chat ZI',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:479806',
    'name': 'Onze Arpents',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16755',
    'name': 'Levasseur',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:479811',
    'name': 'Désiré Lefèvre',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16756',
    'name': 'Levasseur',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:21242',
    'name': 'Onze Arpents',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16704',
    'name': 'Les Clos',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:21205',
    'name': 'Le Chat ZI',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:16670',
    'name': 'Collège Maria Callas',
    'disruptionIds': ['5f95054a-d707-11ef-b937-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02137',
  'name': '4',
  'shortName': '4',
  'mode': 'Bus',
  'networkId': 'network:IDFM:6',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02137',
    'name': '4',
    'disruptionIds': ['d47a59a6-d28d-11ef-b937-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00292',
  'name': '1',
  'shortName': '1',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00292',
    'name': '1',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00324',
  'name': '1',
  'shortName': '1',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00324',
    'name': '1',
    'disruptionIds': ['df941c26-e496-11ef-a3d0-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01473',
  'name': '2',
  'shortName': '2',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01473',
    'name': '2',
    'disruptionIds': ['02ddc486-0560-11f0-8f00-0a58a9feac02',
     '6ab9bef4-f53c-11ef-b375-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01681',
  'name': '3',
  'shortName': '3',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01681',
    'name': '3',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00295',
  'name': '4',
  'shortName': '4',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00295',
    'name': '4',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02',
     '02ddc486-0560-11f0-8f00-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00308',
  'name': '6',
  'shortName': '6',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00308',
    'name': '6',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00312',
  'name': '7',
  'shortName': '7',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00312',
    'name': '7',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00297',
  'name': '8',
  'shortName': '8',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00297',
    'name': '8',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02',
     '02ddc486-0560-11f0-8f00-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00298',
  'name': '9',
  'shortName': '9',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00298',
    'name': '9',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02',
     '02ddc486-0560-11f0-8f00-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00325',
  'name': '12',
  'shortName': '12',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00325',
    'name': '12',
    'disruptionIds': ['c8cfc682-5b90-11ef-b754-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00306',
  'name': '34',
  'shortName': '34',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00306',
    'name': '34',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00310',
  'name': '502 Scolaire',
  'shortName': '502',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00310',
    'name': '502 Scolaire',
    'disruptionIds': ['9881082c-d996-11ef-aa1a-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02149',
  'name': 'B',
  'shortName': 'B',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02149',
    'name': 'B',
    'disruptionIds': ['01884e58-fb38-11ef-829f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00332',
  'name': 'E',
  'shortName': 'E',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00332',
    'name': 'E',
    'disruptionIds': ['c8cfc682-5b90-11ef-b754-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02150',
  'name': 'F',
  'shortName': 'F',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02150',
    'name': 'F',
    'disruptionIds': ['df941c26-e496-11ef-a3d0-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00317',
  'name': 'H',
  'shortName': 'H',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00317',
    'name': 'H',
    'disruptionIds': ['42af8884-f998-11ef-b418-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00316',
  'name': 'J',
  'shortName': 'J',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00316',
    'name': 'J',
    'disruptionIds': ['42af8884-f998-11ef-b418-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00334',
  'name': 'K',
  'shortName': 'K',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00334',
    'name': 'K',
    'disruptionIds': ['09ab280c-e3bf-11ef-803f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00336',
  'name': 'M',
  'shortName': 'M',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00336',
    'name': 'M',
    'disruptionIds': ['c8cfc682-5b90-11ef-b754-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02151',
  'name': 'S5',
  'shortName': 'S5',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02151',
    'name': 'S5',
    'disruptionIds': ['09ab280c-e3bf-11ef-803f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01775',
  'name': 'S6',
  'shortName': 'S6',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1054',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01775',
    'name': 'S6',
    'disruptionIds': ['09ab280c-e3bf-11ef-803f-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02677',
  'name': 'A02 Saint Denis Université',
  'shortName': 'A02 SDU',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1085',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02677',
    'name': 'A02 Saint Denis Université',
    'disruptionIds': ['2fe9811e-f264-11ee-9935-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02678',
  'name': 'A03 Paris La Défense',
  'shortName': 'A03 DEF',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1085',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02678',
    'name': 'A03 Paris La Défense',
    'disruptionIds': ['0258548c-1109-11ef-a614-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02723',
  'name': 'A04 Paris La Villette',
  'shortName': 'A04 VIL',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1085',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02723',
    'name': 'A04 Paris La Villette',
    'disruptionIds': ['a7397530-b0c3-11ef-90f2-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02679',
  'name': 'A05 Disneyland Paris',
  'shortName': 'A05 DIS',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1085',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02679',
    'name': 'A05 Disneyland Paris',
    'disruptionIds': ['a2dd0fe6-f7e2-11ee-9935-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00345',
  'name': '408',
  'shortName': '408',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1063',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00345',
    'name': '408',
    'disruptionIds': ['9a2c4092-cf3c-11ef-b3f5-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00342',
  'name': '412',
  'shortName': '412',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1063',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00342',
    'name': '412',
    'disruptionIds': ['2747d1da-11c3-11f0-b7af-0a58a9feac02',
     '31eec03a-11c3-11f0-bb7e-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:25359',
    'name': 'Petit-Châtenay',
    'disruptionIds': ['2747d1da-11c3-11f0-b7af-0a58a9feac02',
     '31eec03a-11c3-11f0-bb7e-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:35813',
    'name': 'Rue des Vignes',
    'disruptionIds': ['2747d1da-11c3-11f0-b7af-0a58a9feac02',
     '31eec03a-11c3-11f0-bb7e-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:40382',
    'name': 'Rue des Vignes',
    'disruptionIds': ['2747d1da-11c3-11f0-b7af-0a58a9feac02',
     '31eec03a-11c3-11f0-bb7e-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:12101',
    'name': 'Carrefour du 19 Mars 1962',
    'disruptionIds': ['2747d1da-11c3-11f0-b7af-0a58a9feac02',
     '31eec03a-11c3-11f0-bb7e-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01658',
  'name': '415',
  'shortName': '415',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1063',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01658',
    'name': '415',
    'disruptionIds': ['17a16e0a-d1b6-11ef-8d37-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01062',
  'name': 'Express 01',
  'shortName': '01EX',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01062',
    'name': 'Express 01',
    'disruptionIds': ['f752b67a-0984-11f0-ac05-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02070',
  'name': '03B',
  'shortName': '03B',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02070',
    'name': '03B',
    'disruptionIds': ['6124ca8a-f426-11ef-b375-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01063',
  'name': 'Express 17',
  'shortName': '17Ex',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01063',
    'name': 'Express 17',
    'disruptionIds': ['6124ca8a-f426-11ef-b375-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00920',
  'name': '31',
  'shortName': '31',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00920',
    'name': '31',
    'disruptionIds': ['8d333a42-0648-11f0-afbd-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00921',
  'name': '31S',
  'shortName': '31S',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00921',
    'name': '31S',
    'disruptionIds': ['8d333a42-0648-11f0-afbd-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00922',
  'name': '32',
  'shortName': '32',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00922',
    'name': '32',
    'disruptionIds': ['95001646-0648-11f0-9201-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02160',
  'name': '32S',
  'shortName': '32S',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02160',
    'name': '32S',
    'disruptionIds': ['1d10d0ae-0b1a-11f0-8f48-0a58a9feac02',
     '95001646-0648-11f0-9201-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00923',
  'name': '33',
  'shortName': '33',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00923',
    'name': '33',
    'disruptionIds': ['1d10d0ae-0b1a-11f0-8f48-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01993',
  'name': '48',
  'shortName': '48',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01993',
    'name': '48',
    'disruptionIds': ['95001646-0648-11f0-9201-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00934',
  'name': '49',
  'shortName': '49',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00934',
    'name': '49',
    'disruptionIds': ['145c61f6-108f-11f0-bb7e-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00942',
  'name': '56S',
  'shortName': '56S',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00942',
    'name': '56S',
    'disruptionIds': ['1b77da0a-655a-11ef-ae41-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02035',
  'name': 'A',
  'shortName': 'A',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02035',
    'name': 'A',
    'disruptionIds': ['6124ca8a-f426-11ef-b375-0a58a9feac02']}]},
 {'id': 'line:IDFM:C02291',
  'name': 'TàD 43',
  'shortName': 'TàD',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1056',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C02291',
    'name': 'TàD 43',
    'disruptionIds': ['8f5ec8d4-39db-11ef-85e1-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00423',
  'name': '5206 (ex P)',
  'shortName': '5206',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'stop_point',
    'id': 'stop_point:IDFM:5750',
    'name': 'Place Foch',
    'disruptionIds': ['ff5f1896-d80a-11ef-b2cf-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00168',
  'name': '5208 (ex 8)',
  'shortName': '5208',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00168',
    'name': '5208 (ex 8)',
    'disruptionIds': ['9b4c0afe-04be-11f0-8747-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00414',
  'name': '5214 (ex Q)',
  'shortName': '5214',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'stop_point',
    'id': 'stop_point:IDFM:5750',
    'name': 'Place Foch',
    'disruptionIds': ['ff5f1896-d80a-11ef-b2cf-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00422',
  'name': '5219 (ex V)',
  'shortName': '5219',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'stop_point',
    'id': 'stop_point:IDFM:5750',
    'name': 'Place Foch',
    'disruptionIds': ['ff5f1896-d80a-11ef-b2cf-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00177',
  'name': '5224 (ex 24)',
  'shortName': '5224',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00177',
    'name': '5224 (ex 24)',
    'disruptionIds': ['3c7bb8b0-0024-11f0-829f-0a58a9feac02',
     '9b4c0afe-04be-11f0-8747-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00181',
  'name': '5230 (ex 30)',
  'shortName': '5230',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00181',
    'name': '5230 (ex 30)',
    'disruptionIds': ['9b4c0afe-04be-11f0-8747-0a58a9feac02',
     'c236f894-0ec9-11f0-88c2-0a58a9feac02']}]},
 {'id': 'line:IDFM:C01874',
  'name': '5288 (ex FA)',
  'shortName': '5288',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C01874',
    'name': '5288 (ex FA)',
    'disruptionIds': ['bdf5831a-0bed-11f0-88c2-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00424',
  'name': '5289 (ex M)',
  'shortName': '5289',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'stop_point',
    'id': 'stop_point:IDFM:5750',
    'name': 'Place Foch',
    'disruptionIds': ['ff5f1896-d80a-11ef-b2cf-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00182',
  'name': '5301 (ex A)',
  'shortName': '5301',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00182',
    'name': '5301 (ex A)',
    'disruptionIds': ['848d2e90-d4c8-11ef-aa1a-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00184',
  'name': '5303 (ex E)',
  'shortName': '5303',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00184',
    'name': '5303 (ex E)',
    'disruptionIds': ['e79d8690-04bd-11f0-8747-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00163',
  'name': '5311 (ex 1)',
  'shortName': '5311',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00163',
    'name': '5311 (ex 1)',
    'disruptionIds': ['e79d8690-04bd-11f0-8747-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00175',
  'name': '5320 (ex 20)',
  'shortName': '5320',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00175',
    'name': '5320 (ex 20)',
    'disruptionIds': ['3c7bb8b0-0024-11f0-829f-0a58a9feac02',
     '445ed498-dfb5-11ef-b2cf-0a58a9feac02',
     '9b4c0afe-04be-11f0-8747-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00410',
  'name': '5324 (ex 14)',
  'shortName': '5324',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'stop_point',
    'id': 'stop_point:IDFM:5750',
    'name': 'Place Foch',
    'disruptionIds': ['ff5f1896-d80a-11ef-b2cf-0a58a9feac02']},
   {'type': 'stop_point',
    'id': 'stop_point:IDFM:5752',
    'name': 'Rue Andin',
    'disruptionIds': ['ff5f1896-d80a-11ef-b2cf-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00166',
  'name': '5325 (ex 5)',
  'shortName': '5325',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'line',
    'id': 'line:IDFM:C00166',
    'name': '5325 (ex 5)',
    'disruptionIds': ['9b4c0afe-04be-11f0-8747-0a58a9feac02']}]},
 {'id': 'line:IDFM:C00402',
  'name': '5327 (ex 7)',
  'shortName': '5327',
  'mode': 'Bus',
  'networkId': 'network:IDFM:1081',
  'impactedObjects': [{'type': 'stop_point',
    'id': 'stop_point:IDFM:5750',
    'name': 'Place Foch',

## **Convertir les data de la clé diruption en Dataframe** ##

In [358]:
pd.reset_option('display.max_colwidth')

# Normalisation avec l'option errors='ignore' pour ignorer les clés manquantes
df_disruptions = pd.json_normalize(data['disruptions'], 
                                  record_path='applicationPeriods', 
                                  meta=['id', 'lastUpdate', 'cause', 'severity', 'tags', 'title', 'message', 'shortMessage'], 
                                  sep=',', errors='ignore')

# Affichage du résultat
df_disruptions.head()

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage
0,20241012T020900,20241013T233400,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN
1,20241019T120900,20241020T230900,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN
2,20241207T020900,20241208T234400,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN
3,20250118T020900,20250119T234900,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN
4,20250329T020900,20250330T235400,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN

## **Convertir les data de la clé lines en Dataframe** ##

In [359]:
from collections import defaultdict

# 1. Créer un dictionnaire pour lier disruptionId aux arrêts concernés
disruption_to_stops = defaultdict(set)

# 2. Remplir ce dictionnaire et ajouter les informations 'name' et 'mode' à chaque disruptionId
disruption_line_info = {}  # Dictionnaire pour lier disruptionId aux informations de ligne (name, mode)

for line in lines:
    for obj in line.get('impactedObjects', []):
        if obj['type'] == 'stop_point':  # Filtrer uniquement les objets de type 'stop_point'
            stop_name = obj['name']
            for disruption_id in obj.get('disruptionIds', []):
                # Ajouter l'arrêt à la liste des arrêts pour ce disruptionId
                disruption_to_stops[disruption_id].add(stop_name)
                # Ajouter les informations de la ligne (name, mode) pour ce disruptionId
                if disruption_id not in disruption_line_info:
                    disruption_line_info[disruption_id] = {
                        'name': line['name'],
                        'mode': line['mode']
                    }

# 3. Construction du DataFrame avec les arrêts pour chaque disruptionId
df_lines = pd.DataFrame([
    {
        'disruptionId': disruption_id,
        'stop_points': sorted(list(stops)),
        'name': disruption_line_info[disruption_id]['name'],
        'mode': disruption_line_info[disruption_id]['mode'],
        
    }
    for disruption_id, stops in disruption_to_stops.items()
])

# Affichage du DataFrame final
df_lines.head()

,disruptionId,stop_points,name,mode
0,4884f0e6-00cd-11f0-af9a-0a58a9feac02,"[Ampère, Rond-Point des Sciences]",1,Bus
1,5f95054a-d707-11ef-b937-0a58a9feac02,"[Collège Maria Callas, Désiré Lefèvre, Le Chat...",3,Bus
2,2747d1da-11c3-11f0-b7af-0a58a9feac02,"[Carrefour du 19 Mars 1962, Petit-Châtenay, Ru...",412,Bus
3,31eec03a-11c3-11f0-bb7e-0a58a9feac02,"[Carrefour du 19 Mars 1962, Petit-Châtenay, Ru...",412,Bus
4,ff5f1896-d80a-11ef-b2cf-0a58a9feac02,"[Place Foch, Rue Andin]",5206 (ex P),Bus

## **Filtrer évènements en cours du dataset disruptions** ##

In [360]:
from datetime import datetime

def filtrer_evenements_en_cours(df, col_debut="begin", col_fin="end", now=None):
    """
    Filtre les événements en cours à partir d'un DataFrame avec colonnes 'start' et 'end' (format 'YYYYMMDDTHHMMSS').

    :param df: DataFrame contenant les événements
    :param col_debut: nom de la colonne de début (par défaut "start")
    :param col_fin: nom de la colonne de fin (par défaut "end")
    :param now: datetime personnalisé (utile pour les tests), sinon datetime.now()
    :return: DataFrame filtré avec les événements en cours
    """
    df = df.copy()
    
    # Conversion des dates
    df[col_debut] = pd.to_datetime(df[col_debut], format="%Y%m%dT%H%M%S", errors='coerce')
    df[col_fin] = pd.to_datetime(df[col_fin], format="%Y%m%dT%H%M%S", errors='coerce')

    # Date/heure actuelle
    now = now or pd.Timestamp.now()

    # Filtrage des événements en cours
    df_en_cours = df[(df[col_debut] <= now) & (df[col_fin] >= now)]
    
    return df_en_cours

In [361]:
df_en_cours = filtrer_evenements_en_cours(df_disruptions)
df_en_cours.head()

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage
5,2025-04-05 03:04:00,2025-04-06 23:49:00,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,<p>En raison de travaux boulevard Carnot et Ca...,NaN
35,2025-01-06 01:00:00,2025-06-06 23:00:00,4a2946e2-beae-11ef-b1c7-0a58a9feac02,20241220T094303,TRAVAUX,BLOQUANTE,NaN,"4414, 4438 et TàD Etréchy, Travaux Chauffour-l...","<p>Lignes 4414, 4438 et TàD Etréchy, du 6/01/2...",NaN
542,2025-01-13 00:00:00,2025-12-31 23:59:00,30376efa-cea6-11ef-8d37-0a58a9feac02,20250109T172424,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,<p>En raison de travaux avenue Jean Jaurès à M...,NaN
543,2025-01-13 00:00:00,2025-06-30 23:59:00,426b148c-ceab-11ef-8d37-0a58a9feac02,20250313T203153,TRAVAUX,BLOQUANTE,NaN,🚧 5121 5152 - Travaux : Arrêt Golf National da...,<p><strong>🚧 #Perturbations #Ligne5121 #Ligne5...,NaN
544,2025-01-12 00:31:00,2025-12-24 00:31:00,dead0f6a-d079-11ef-b1c7-0a58a9feac02,20250112T011211,TRAVAUX,BLOQUANTE,NaN,Bus N21 : Travaux - Arrêt(s) non desservi(s),<p>La ligne N21 est déviée : les arrêts situés...,NaN

## **Merged dataset disruptions et lines sur les clés communes disruptionId et id** ##

In [362]:
# On renomme "disruptionId" en "id" dans df_lines pour pouvoir faire la jointure facilement
df_lines_renamed = df_lines.rename(columns={'disruptionId': 'id'})

# Merge (left join) : on garde tout df_en_cours, et on ajoute les colonnes de df_lines si id commun
df_merged = df_en_cours.merge(df_lines_renamed, on='id', how='left')

## **PREPROCESSING** ##

In [363]:
from bs4 import BeautifulSoup

# Supprimer valeurs NAN et converttir en str
df_merged['message'] = df_merged['message'].astype(str).fillna('')

# Appliquer la suppression des balises HTML à chaque message de la colonne 'message'
df_merged['message'] = df_merged['message'].apply(
    lambda msg: BeautifulSoup(msg, "html.parser").get_text()
)

In [364]:
df_merged.head()

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode
0,2025-04-05 03:04:00,2025-04-06 23:49:00,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,En raison de travaux boulevard Carnot et Calme...,NaN,NaN,NaN,NaN
1,2025-01-06 01:00:00,2025-06-06 23:00:00,4a2946e2-beae-11ef-b1c7-0a58a9feac02,20241220T094303,TRAVAUX,BLOQUANTE,NaN,"4414, 4438 et TàD Etréchy, Travaux Chauffour-l...","Lignes 4414, 4438 et TàD Etréchy, du 6/01/2025...",NaN,[Grande Rue],4414,Bus
2,2025-01-13 00:00:00,2025-12-31 23:59:00,30376efa-cea6-11ef-8d37-0a58a9feac02,20250109T172424,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,En raison de travaux avenue Jean Jaurès à Mant...,NaN,[Poste],21,Bus
3,2025-01-13 00:00:00,2025-06-30 23:59:00,426b148c-ceab-11ef-8d37-0a58a9feac02,20250313T203153,TRAVAUX,BLOQUANTE,NaN,🚧 5121 5152 - Travaux : Arrêt Golf National da...,🚧 #Perturbations #Ligne5121 #Ligne5152📅 à part...,NaN,[Golf National],5121,Bus
4,2025-01-12 00:31:00,2025-12-24 00:31:00,dead0f6a-d079-11ef-b1c7-0a58a9feac02,20250112T011211,TRAVAUX,BLOQUANTE,NaN,Bus N21 : Travaux - Arrêt(s) non desservi(s),La ligne N21 est déviée : les arrêts situés en...,NaN,"[Barbusse - Larroumes, Carrefour des Poulets, ...",N21,Bus

In [365]:
# Récupérer les ID des perturbations du précédent appel API
# Par exemple, ces ID pourraient être stockés dans un fichier ou une base de données.
previous_disruptions = set(df_merged['id'].tolist())

# Simulons un nouvel appel API en modifiant df_merged pour représenter le nouvel état des perturbations
# Ce dataframe (df_merged) serait mis à jour à chaque appel API avec de nouvelles données.
new_disruptions = set(df_merged['id'].tolist())  # Ici on reprend la même liste, mais dans un vrai cas, ce serait mis à jour.

# Ajouter la colonne 'status' en fonction des conditions
df_merged['status'] = df_merged['id'].apply(
    lambda x: 'new' if x not in previous_disruptions else ('finished' if x not in new_disruptions else 'now')
)

# Afficher le DataFrame avec la nouvelle colonne 'status'
df_merged.head()

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode,status
0,2025-04-05 03:04:00,2025-04-06 23:49:00,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,En raison de travaux boulevard Carnot et Calme...,NaN,NaN,NaN,NaN,now
1,2025-01-06 01:00:00,2025-06-06 23:00:00,4a2946e2-beae-11ef-b1c7-0a58a9feac02,20241220T094303,TRAVAUX,BLOQUANTE,NaN,"4414, 4438 et TàD Etréchy, Travaux Chauffour-l...","Lignes 4414, 4438 et TàD Etréchy, du 6/01/2025...",NaN,[Grande Rue],4414,Bus,now
2,2025-01-13 00:00:00,2025-12-31 23:59:00,30376efa-cea6-11ef-8d37-0a58a9feac02,20250109T172424,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,En raison de travaux avenue Jean Jaurès à Mant...,NaN,[Poste],21,Bus,now
3,2025-01-13 00:00:00,2025-06-30 23:59:00,426b148c-ceab-11ef-8d37-0a58a9feac02,20250313T203153,TRAVAUX,BLOQUANTE,NaN,🚧 5121 5152 - Travaux : Arrêt Golf National da...,🚧 #Perturbations #Ligne5121 #Ligne5152📅 à part...,NaN,[Golf National],5121,Bus,now
4,2025-01-12 00:31:00,2025-12-24 00:31:00,dead0f6a-d079-11ef-b1c7-0a58a9feac02,20250112T011211,TRAVAUX,BLOQUANTE,NaN,Bus N21 : Travaux - Arrêt(s) non desservi(s),La ligne N21 est déviée : les arrêts situés en...,NaN,"[Barbusse - Larroumes, Carrefour des Poulets, ...",N21,Bus,now

## **Ouvrir le précédent appel API s'il existe** ##

In [366]:
# Charger le fichier CSV de la version précédente
previous_file = "df_previous_merged.csv"

try:
    df_previous = pd.read_csv(previous_file)
    print("Fichier précédent chargé depuis CSV.")
except FileNotFoundError:
    df_previous = pd.DataFrame(columns=["id", "name", "mode", "begin", "end", "severity", "tags", "title", "message", "status"])
    print("Aucun fichier précédent trouvé, c’est le premier appel ?")

Fichier précédent chargé depuis CSV.

## **Remplacer l'ancien appel API par l'actuel qui deviendra lui même l'ancien appel API** ##

In [367]:
df_merged.to_csv(f"df_previous_merged.csv", index=False)

In [368]:
df_current = df_merged

## **Mise à jour du statut des disruptions : nouvelles, en cours, terminées** ##

In [369]:
# Ajouter la colonne 'status' pour les disruptions actuelles
df_current["status"] = df_current["id"].apply(
    lambda x: "new" if x not in df_previous["id"].values else "now"
)

# Identifier les disruptions terminées ("finished")
finished_ids = set(df_previous["id"]) - set(df_current["id"])
df_finished = df_previous[df_previous["id"].isin(finished_ids)].copy()
df_finished["status"] = "finished"  # Ajouter le statut "finished"

## **Concaténer les résultats** ##

In [370]:
# Fusionner les disruptions actuelles et terminées
df_all = pd.concat([df_current, df_finished], ignore_index=True)

In [371]:
df_all.head()

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode,status
0,2025-04-05 03:04:00,2025-04-06 23:49:00,74316236-8627-11ef-aca5-0a58a9feac02,20250401T120646,TRAVAUX,BLOQUANTE,[Actualité],Travaux boulevard Carnot et Calmette,En raison de travaux boulevard Carnot et Calme...,NaN,NaN,NaN,NaN,now
1,2025-01-06 01:00:00,2025-06-06 23:00:00,4a2946e2-beae-11ef-b1c7-0a58a9feac02,20241220T094303,TRAVAUX,BLOQUANTE,NaN,"4414, 4438 et TàD Etréchy, Travaux Chauffour-l...","Lignes 4414, 4438 et TàD Etréchy, du 6/01/2025...",NaN,[Grande Rue],4414,Bus,now
2,2025-01-13 00:00:00,2025-12-31 23:59:00,30376efa-cea6-11ef-8d37-0a58a9feac02,20250109T172424,TRAVAUX,BLOQUANTE,[Actualité],Fermeture avenue Jean Jaurès à Mantes-la-Ville...,En raison de travaux avenue Jean Jaurès à Mant...,NaN,[Poste],21,Bus,now
3,2025-01-13 00:00:00,2025-06-30 23:59:00,426b148c-ceab-11ef-8d37-0a58a9feac02,20250313T203153,TRAVAUX,BLOQUANTE,NaN,🚧 5121 5152 - Travaux : Arrêt Golf National da...,🚧 #Perturbations #Ligne5121 #Ligne5152📅 à part...,NaN,[Golf National],5121,Bus,now
4,2025-01-12 00:31:00,2025-12-24 00:31:00,dead0f6a-d079-11ef-b1c7-0a58a9feac02,20250112T011211,TRAVAUX,BLOQUANTE,NaN,Bus N21 : Travaux - Arrêt(s) non desservi(s),La ligne N21 est déviée : les arrêts situés en...,NaN,"[Barbusse - Larroumes, Carrefour des Poulets, ...",N21,Bus,now

In [376]:
df_all['mode'].value_counts()

mode
Bus             232
RapidTransit      4
LocalTrain        3
Tramway           1
Metro             1
Name: count, dtype: int64

## **Filtrer les disruptions concernant le réseau férré** ##

In [ ]:
df_all_filtered = df_all[df_all['mode'].isin(['RapidTransit', 'LocalTrain', 'Tramway', 'Metro'])]

In [380]:
df_all_filtered.shape

(9, 14)

In [379]:
df_all_filtered.head(10)

,begin,end,id,lastUpdate,cause,severity,tags,title,message,shortMessage,stop_points,name,mode,status
47,2025-04-05 23:30:00,2025-04-07 02:30:00,7750a9c6-0594-11f0-8f00-0a58a9feac02,20250320T150606,TRAVAUX,BLOQUANTE,[Actualité],RER C : Auster.-Choisy-Juvisy 05/04 au 06/04.,Période : à partir de 23h45 jusqu’en fin de so...,Trafic interrompu planifié,"[Ablon, Arpajon, Athis-Mons, Bibliothèque Fran...",C,RapidTransit,now
48,2025-04-06 03:00:00,2025-04-07 03:00:00,cff4d016-0594-11f0-949f-0a58a9feac02,20250320T150835,TRAVAUX,BLOQUANTE,[Actualité],RER C: Massy P.- Pt de Rungis 6-12-13-26-27 avril,Période : Toute la journée.Date : le dimanche...,Trafic interrompu planifié,"[Bibliothèque François Mitterrand, Chemin d'An...",C,RapidTransit,now
73,2025-03-27 18:42:00,2025-04-22 04:30:00,26847bb8-0b33-11f0-b7af-0a58a9feac02,20250327T184436,TRAVAUX,BLOQUANTE,[Actualité],Tramway T1 : Travaux - Trafic interrompu,"Jusqu'au lundi 21 avril 2025, le trafic est in...",Trafic interrompu,"[Auguste Delaune, Bobigny - Pablo Picasso, Esc...",T1,Tramway,now
87,2025-04-06 03:00:00,2025-04-07 03:00:00,29d01dd4-0edc-11f0-8f48-0a58a9feac02,20250401T113201,TRAVAUX,BLOQUANTE,[Actualité],ligne N : Bellevue non desservi du 05 au 06/04,Période : du premier au dernier trainDates : d...,Arrêt non desservi planifié,"[Chaville Rive Gauche, Clamart, Coignières, Dr...",N,LocalTrain,now
88,2025-04-06 03:00:00,2025-04-07 03:00:00,171a3cca-0ee0-11f0-ac05-0a58a9feac02,20250401T120007,TRAVAUX,BLOQUANTE,[Actualité],RER C : Choisy-Juvisy 05/04 au 06/04.,Période : Tout le week-end.Dates : Samedi 5 et...,Arrêts non desservis planifiés,"[Ablon, Arpajon, Athis-Mons, Bouray, Breuillet...",C,RapidTransit,now
143,2025-04-06 03:00:00,2025-04-07 03:00:00,f08ac200-11cd-11f0-b7af-0a58a9feac02,20250405T052745,TRAVAUX,BLOQUANTE,[Actualité],Ligne V : Versailles-Chantiers / Massy P 5-6-1...,Période : Tout le week-end.Dates : les week-en...,Trafic interrompu planifié,"[Bièvres, Igny, Jouy-en-Josas, Massy - Palaise...",V,LocalTrain,now
247,2025-04-06 20:09:06,2025-04-06 21:45:00,38cc8a04-1317-11f0-88c2-0a58a9feac02,20250406T204450,PERTURBATION,BLOQUANTE,[Actualité],Ligne N : Dreux <-> Plaisir - Grignon trafic i...,Le trafic est interrompu entre Dreux et Plaisi...,interruption,"[Chaville Rive Gauche, Clamart, Dreux, Fontena...",N,LocalTrain,now
364,2025-04-06 20:11:22,2025-04-06 22:45:00,1be00b94-1314-11f0-88c2-0a58a9feac02,20250406T202234,PERTURBATION,PERTURBEE,[Actualité],RER E : perturbations,Le trafic est perturbé entre Nanterre-La-Folie...,fortement ralenti,"[Gretz-Armainvilliers, Haussmann Saint-Lazare,...",E,RapidTransit,now
366,2025-04-06 21:16:41,2025-04-06 21:40:04,2a1c30b8-131c-11f0-bb7e-0a58a9feac02,20250406T212013,PERTURBATION,PERTURBEE,[Actualité],Métro 10 : Panne de portes de train - Train st...,Un train stationne à Boulogne Jean Jaurès en d...,Train stationne,[Boulogne Jean Jaurès],10,Metro,new

In [374]:
df_all.status.value_counts()

status
now         453
new           1
finished      1
Name: count, dtype: int64

Comment lire les indications temporelles

begin 20241012T020900

2024 : Année

10 : Mois (octobre)

12 : Jour

T : Séparateur entre la date et l'heure (utilisé pour indiquer que ce qui suit est l'heure)

02 : Heure (2 heures du matin)

09 : Minute

00 : Seconde